import type{ProjectionOptions,ProjectionView}from'./drr';
import type{PatientSex}from'./patients';
import type{FullBodyPose,RadiographicPosition}from'./radiographic-positions';
export type Vec3=readonly[number,number,number];
export interface CollimationEdges{left:number;right:number;top:number;bottom:number}
export interface AcquisitionState{examination:{id:string;region:string;projection:string;view:ProjectionView;patientSex:PatientSex};patient:{pose:FullBodyPose;translationPercent:Vec3;rotationDeg:Vec3};detector:{orientation:'portrait'|'landscape';dimensionsCm:readonly[number,number];centreMm:Vec3;normal:Vec3;up:Vec3};source:{positionMm:Vec3;sidCm:number;tubeAngleDeg:number;centralRayTargetMm:Vec3};beam:{centrePercent:readonly[number,number];collimation:CollimationEdges};exposure:{kVp:number;mAs:number}}
export interface AcquisitionInput{position:RadiographicPosition;patientSex:PatientSex;bodyYawDeg:number;patientXPercent:number;patientYPercent:number;beamXPercent:number;beamYPercent:number;tubeAngleDeg:number;sidCm:number;kVp:number;mAs:number;collimation:CollimationEdges}
export function projectionView(projection:string):ProjectionView{const value=projection.trim().toUpperCase();return value.includes('LATERAL')?'LATERAL':value.startsWith('AP')?'AP':'PA'}
/** Build the immutable exposure record shared by positioning, projection and critique. */
export function createAcquisitionState(input:AcquisitionInput):AcquisitionState{const{position}=input,view=projectionView(position.projection),landscape=position.detector==='landscape',dimensionsCm=landscape?[43,35]as const:[35,43]as const,centreX=input.beamXPercent-input.patientXPercent,centreY=input.beamYPercent-input.patientYPercent,sidMm=input.sidCm*10,angle=Math.tan(input.tubeAngleDeg*Math.PI/180)*sidMm,detector={orientation:position.detector,dimensionsCm,centreMm:[0,0,0]as Vec3,normal:(view==='LATERAL'?[1,0,0]:[0,view==='PA'?1:-1,0])as Vec3,up:[0,0,1]as Vec3},sourcePosition:Vec3=view==='LATERAL'?[-sidMm,0,-angle]:[0,(view==='PA'?1:-1)*sidMm,-angle];return{examination:{id:position.id,region:position.region,projection:position.projection,view,patientSex:input.patientSex},patient:{pose:position.pose,translationPercent:[input.patientXPercent,input.patientYPercent,0],rotationDeg:[position.pose.bodyPitch,input.bodyYawDeg,position.pose.bodyRoll]},detector,source:{positionMm:sourcePosition,sidCm:input.sidCm,tubeAngleDeg:input.tubeAngleDeg,centralRayTargetMm:[centreX/100*dimensionsCm[0]*10,0,centreY/100*dimensionsCm[1]*10]},beam:{centrePercent:[centreX,centreY],collimation:{...input.collimation}},exposure:{kVp:input.kVp,mAs:input.mAs}}}
export function projectionOptions(state:AcquisitionState,seed=17):ProjectionOptions{return{view:state.examination.view,stepVoxels:3,kVp:state.exposure.kVp,mAs:state.exposure.mAs,sidCm:state.source.sidCm,rotationDeg:state.patient.rotationDeg[1],collimation:{...state.beam.collimation},centreXPercent:state.beam.centrePercent[0],centreYPercent:state.beam.centrePercent[1],tubeAngleDeg:state.source.tubeAngleDeg,detectorWidthCm:state.detector.dimensionsCm[0],detectorHeightCm:state.detector.dimensionsCm[1],seed}}
