export type ContrastPhase='none'|'arterial'|'portal-venous'|'delayed'|'split-bolus'|'enteric';
export type CtAnatomyRegion='head'|'neck'|'chest'|'aorta'|'cap'|'abdomen-pelvis'|'kub'|'colon'|'trauma';
export interface CtProtocol{ id:string;label:string;region:CtAnatomyRegion;anatomy:string;coverage:string;coverageLandmarks:string[];contrast:ContrastPhase[];defaultPhase:ContrastPhase;windowKeys:string[];reconstructions:string[];detailTarget:string;notes:string }
// Teaching protocol definitions describe the anatomy that a dedicated acquisition must contain.
// They must not be implemented as arbitrary percentage crops of a whole-body volume. Coverage is
// resolved from anatomical landmarks/segmentations for each male/female source volume.
export const CT_PROTOCOLS:CtProtocol[]=[
{id:'head-nc',label:'Head — non-contrast',region:'head',anatomy:'Brain, calvarium and skull base',coverage:'C2/skull base to vertex',coverageLandmarks:['c2','skull_base','vertex'],contrast:['none'],defaultPhase:'none',windowKeys:['brain','bone'],reconstructions:['thin axial','axial brain','coronal brain','sagittal brain','axial bone','coronal bone','sagittal bone'],detailTarget:'Sub-millimetre source/reconstruction target where source data permits; preserve posterior fossa and skull-base detail.',notes:'Dedicated head acquisition; not a whole-body slice selector.'},
{id:'head-contrast',label:'Head — post contrast',region:'head',anatomy:'Brain, intracranial structures, calvarium and skull base',coverage:'C2/skull base to vertex',coverageLandmarks:['c2','skull_base','vertex'],contrast:['portal-venous'],defaultPhase:'portal-venous',windowKeys:['brain','bone'],reconstructions:['thin axial','axial brain','coronal brain','sagittal brain'],detailTarget:'Dedicated high-detail head volume with the complete cranial vault and skull base.',notes:'Post-contrast run requires a true enhanced volume; display brightness must not imitate enhancement.'},
{id:'neck',label:'Neck',region:'neck',anatomy:'Skull base, pharynx/larynx, cervical soft tissues and thoracic inlet',coverage:'Skull base through thoracic inlet',coverageLandmarks:['skull_base','thoracic_inlet'],contrast:['none','portal-venous'],defaultPhase:'portal-venous',windowKeys:['soft'],reconstructions:['thin axial','coronal soft tissue','sagittal soft tissue'],detailTarget:'Small-FOV neck reconstruction retaining airway, glands, vessels, nodes and cervical spine.',notes:'Coverage and phase vary with indication.'},
{id:'chest',label:'Chest',region:'chest',anatomy:'Lungs, pleura, mediastinum, heart and thoracic skeleton',coverage:'Above lung apices through costophrenic recesses/lung bases',coverageLandmarks:['lung_apices','lung_bases'],contrast:['none','portal-venous'],defaultPhase:'portal-venous',windowKeys:['lung','soft','bone'],reconstructions:['thin axial','coronal lung','sagittal lung','mediastinal'],detailTarget:'Thin-section thoracic source sufficient for lung, airway and mediastinal detail.',notes:'Dedicated thoracic acquisition.'},
{id:'ctpa',label:'CTPA',region:'chest',anatomy:'Pulmonary arterial tree and thorax',coverage:'Thoracic inlet through lung bases',coverageLandmarks:['thoracic_inlet','lung_bases'],contrast:['arterial'],defaultPhase:'arterial',windowKeys:['soft','lung'],reconstructions:['thin axial vascular','coronal vascular','sagittal vascular'],detailTarget:'Thin-section chest with pulmonary arterial opacification and peripheral vessel detail.',notes:'Requires a true pulmonary-arterial enhanced run.'},
{id:'aorta',label:'CT Aorta',region:'aorta',anatomy:'Aorta and branch vessels with adjacent anatomy',coverage:'Indication-specific aortic segment; whole aorta when selected',coverageLandmarks:['aortic_arch','aortic_bifurcation'],contrast:['none','arterial','delayed'],defaultPhase:'arterial',windowKeys:['soft','bone'],reconstructions:['thin axial vascular','coronal vascular','sagittal vascular'],detailTarget:'Thin vascular reconstruction preserving lumen, wall and branch-vessel anatomy.',notes:'Exact superior/inferior extent depends on the aortic indication.'},
{id:'cap',label:'Chest, abdomen & pelvis',region:'cap',anatomy:'Thorax, abdominal viscera and pelvis',coverage:'Above lung apices through pubic symphysis',coverageLandmarks:['lung_apices','pubic_symphysis'],contrast:['none','arterial','portal-venous'],defaultPhase:'portal-venous',windowKeys:['soft','lung','bone'],reconstructions:['thin axial','coronal soft tissue','sagittal soft tissue','lung'],detailTarget:'Full diagnostic body coverage with organ-specific soft-tissue and lung reconstructions.',notes:'Multiphasic runs may use different anatomical ranges.'},
{id:'abdomen-pelvis',label:'Abdomen & pelvis',region:'abdomen-pelvis',anatomy:'Abdominal and pelvic viscera',coverage:'Diaphragmatic domes through pubic symphysis',coverageLandmarks:['diaphragm','pubic_symphysis'],contrast:['none','arterial','portal-venous','delayed'],defaultPhase:'portal-venous',windowKeys:['soft','bone'],reconstructions:['thin axial','coronal soft tissue','sagittal soft tissue'],detailTarget:'Abdominopelvic volume retaining solid-organ, bowel, urinary and pelvic detail.',notes:'Phase selected by indication.'},
{id:'kub',label:'CT KUB',region:'kub',anatomy:'Kidneys, ureters and urinary bladder',coverage:'Upper renal poles through bladder base/pubic symphysis',coverageLandmarks:['kidney_upper_poles','bladder_base','pubic_symphysis'],contrast:['none'],defaultPhase:'none',windowKeys:['soft','bone'],reconstructions:['thin axial','coronal urinary tract','sagittal'],detailTarget:'Thin enough to retain small urinary calculi throughout both collecting systems and ureters.',notes:'Dedicated non-contrast urinary-tract acquisition.'},
{id:'colonography',label:'CT Colonography',region:'colon',anatomy:'Colon and surrounding abdomen/pelvis',coverage:'Entire distended colon and abdomen/pelvis',coverageLandmarks:['diaphragm','rectum'],contrast:['enteric','portal-venous'],defaultPhase:'enteric',windowKeys:['soft'],reconstructions:['thin supine','thin prone','coronal','sagittal'],detailTarget:'Thin-section colonic dataset suitable for multiplanar and endoluminal teaching views.',notes:'Requires dedicated prepared/distended/tagged bowel data rather than a generic abdominal crop.'},
{id:'major-trauma',label:'Major Trauma',region:'trauma',anatomy:'Head, cervical spine, thorax, abdomen and pelvis',coverage:'Phase-specific trauma acquisitions',coverageLandmarks:['vertex','skull_base','lung_apices','pubic_symphysis'],contrast:['none','split-bolus','arterial','portal-venous','delayed'],defaultPhase:'split-bolus',windowKeys:['brain','lung','soft','bone'],reconstructions:['head brain/bone','cervical spine','thin body axial','coronal body','sagittal body'],detailTarget:'Separate high-detail head/spine and body reconstructions; do not substitute one low-resolution whole-body series.',notes:'Supports separate non-contrast head and contrast-enhanced body runs; exact strategy varies locally.'}
];
export const protocolById=(id:string)=>CT_PROTOCOLS.find(p=>p.id===id)??CT_PROTOCOLS[0];
