import type{PatientSex}from'./patients';
import type{CtAnatomyRegion,CtProtocol,ContrastPhase}from'./ct-protocols';
export interface CtSeriesDescriptor{id:string;sex:PatientSex;region:CtAnatomyRegion;phase:ContrastPhase;manifestUrl:string;coverageLandmarks:string[];reconstruction:string;detail:string;availability:'ready'|'build-required'}
const LANDMARKS:Partial<Record<CtAnatomyRegion,string[]>>={head:['vertex','skull_base'],neck:['skull_base','thoracic_inlet'],chest:['lung_apices','lung_bases'],cap:['lung_apices','pubic_symphysis'],'abdomen-pelvis':['diaphragm','pubic_symphysis'],kub:['kidney_upper_poles','bladder_base','pubic_symphysis']};
function regional(sex:PatientSex,region:CtAnatomyRegion,phase:ContrastPhase,path=region):CtSeriesDescriptor{return{id:ctSeriesId(sex,region,phase),sex,region,phase,manifestUrl:`/cases/regional/${sex}/${path}/manifest.json`,coverageLandmarks:LANDMARKS[region]??[],reconstruction:'thin-axial',detail:'Verified segmentation-bounded source HU volume.',availability:'ready'}}
// Verified outputs from the successful regional anatomy build. Source voxels are unenhanced, so
// only phase=none is registered. Enhanced protocols remain unavailable until true 3-D phase volumes exist.
export const CT_SERIES:CtSeriesDescriptor[]=[regional('male','head','none'),regional('male','neck','none'),regional('male','chest','none'),regional('male','cap','none'),regional('male','abdomen-pelvis','none'),regional('male','kub','none')];
export function ctSeriesId(sex:PatientSex,region:CtAnatomyRegion,phase:ContrastPhase,reconstruction='thin-axial'){return`${sex}-${region}-${phase}-${reconstruction}`}
export function ctSeriesManifestUrl(sex:PatientSex,protocol:CtProtocol,phase:ContrastPhase){return`/cases/ct/${sex}/${protocol.region}/${phase}/manifest.json`}
export function resolveCtSeries(sex:PatientSex,protocol:CtProtocol,phase:ContrastPhase,reconstruction='thin-axial'){return CT_SERIES.find(s=>s.sex===sex&&s.region===protocol.region&&s.phase===phase&&s.reconstruction===reconstruction&&s.availability==='ready')??null}
export function expectedCtSeries(sex:PatientSex,protocol:CtProtocol,phase:ContrastPhase):CtSeriesDescriptor{return{id:ctSeriesId(sex,protocol.region,phase),sex,region:protocol.region,phase,manifestUrl:ctSeriesManifestUrl(sex,protocol,phase),coverageLandmarks:protocol.coverageLandmarks,reconstruction:'thin-axial',detail:protocol.detailTarget,availability:'build-required'}}
export function assertDedicatedCtSeries(series:CtSeriesDescriptor|null,protocol:CtProtocol):CtSeriesDescriptor{if(!series)throw new Error(`${protocol.label} acquisition unavailable — dedicated ${protocol.coverage} volume required`);return series}
