import type{PatientSex}from'./patients';
import type{CtAnatomyRegion,CtProtocol,ContrastPhase}from'./ct-protocols';
export interface CtSeriesDescriptor{id:string;sex:PatientSex;region:CtAnatomyRegion;phase:ContrastPhase;manifestUrl:string;coverageLandmarks:string[];reconstruction:string;detail:string;availability:'ready'|'build-required';dataKind:'acquired'|'simulated-phase';sourcePhase:'none'}
const LANDMARKS:Partial<Record<CtAnatomyRegion,string[]>>={head:['vertex','skull_base'],neck:['skull_base','thoracic_inlet'],chest:['lung_apices','lung_bases'],cap:['lung_apices','pubic_symphysis'],'abdomen-pelvis':['diaphragm','pubic_symphysis'],kub:['kidney_upper_poles','bladder_base','pubic_symphysis']};
function regional(sex:PatientSex,region:CtAnatomyRegion,phase:ContrastPhase,path=region,dataKind:'acquired'|'simulated-phase'='acquired'):CtSeriesDescriptor{return{id:ctSeriesId(sex,region,phase),sex,region,phase,manifestUrl:`/cases/regional/${sex}/${path}/manifest.json`,coverageLandmarks:LANDMARKS[region]??[],reconstruction:'thin-axial',detail:dataKind==='simulated-phase'?'Educational contrast phase generated from the verified segmentation-bounded source HU anatomy; not an acquired enhanced series.':'Verified segmentation-bounded source HU volume.',availability:'ready',dataKind,sourcePhase:'none'}}
const SIMULATED_PHASES:Partial<Record<CtAnatomyRegion,ContrastPhase[]>>={head:['portal-venous'],neck:['portal-venous'],chest:['portal-venous','arterial'],cap:['arterial','portal-venous'], 'abdomen-pelvis':['arterial','portal-venous','delayed']};
const BASE_REGIONS:CtAnatomyRegion[]=['head','neck','chest','cap','abdomen-pelvis','kub'];
export const CT_SERIES:CtSeriesDescriptor[]=[...BASE_REGIONS.map(region=>regional('male',region,'none')),...BASE_REGIONS.flatMap(region=>(SIMULATED_PHASES[region]??[]).map(phase=>regional('male',region,phase,region,'simulated-phase')))];
export function ctSeriesId(sex:PatientSex,region:CtAnatomyRegion,phase:ContrastPhase,reconstruction='thin-axial'){return`${sex}-${region}-${phase}-${reconstruction}`}
export function ctSeriesManifestUrl(sex:PatientSex,protocol:CtProtocol,phase:ContrastPhase){return`/cases/ct/${sex}/${protocol.region}/${phase}/manifest.json`}
export function resolveCtSeries(sex:PatientSex,protocol:CtProtocol,phase:ContrastPhase,reconstruction='thin-axial'){return CT_SERIES.find(s=>s.sex===sex&&s.region===protocol.region&&s.phase===phase&&s.reconstruction===reconstruction&&s.availability==='ready')??null}
export function expectedCtSeries(sex:PatientSex,protocol:CtProtocol,phase:ContrastPhase):CtSeriesDescriptor{return{id:ctSeriesId(sex,protocol.region,phase),sex,region:protocol.region,phase,manifestUrl:ctSeriesManifestUrl(sex,protocol,phase),coverageLandmarks:protocol.coverageLandmarks,reconstruction:'thin-axial',detail:protocol.detailTarget,availability:'build-required',dataKind:'acquired',sourcePhase:'none'}}
export function assertDedicatedCtSeries(series:CtSeriesDescriptor|null,protocol:CtProtocol):CtSeriesDescriptor{if(!series)throw new Error(`${protocol.label} acquisition unavailable — dedicated ${protocol.coverage} volume required`);return series}
