import type{TeachingVolume}from'./teaching-volume';
export interface CtWindow{center:number;width:number;label:string}
export type CtPlane='axial'|'coronal'|'sagittal';
export const CT_WINDOWS={soft:{center:40,width:400,label:'Soft tissue'},lung:{center:-600,width:1500,label:'Lung'},bone:{center:400,width:1800,label:'Bone'},brain:{center:40,width:80,label:'Brain'}} satisfies Record<string,CtWindow>;
export function windowHu(hu:number,w:CtWindow){const lo=w.center-w.width/2,hi=w.center+w.width/2;if(hu<=lo)return 0;if(hu>=hi)return 255;return Math.round((hu-lo)/(hi-lo)*255)}
function lerp(a:number,b:number,t:number){return a+(b-a)*t}
function sample(v:TeachingVolume,x:number,y:number,z:number){const[nx,ny,nz]=v.source.manifest.dimensions,x0=Math.max(0,Math.min(nx-1,Math.floor(x))),y0=Math.max(0,Math.min(ny-1,Math.floor(y))),z0=Math.max(0,Math.min(nz-1,Math.floor(z))),x1=Math.min(nx-1,x0+1),y1=Math.min(ny-1,y0+1),z1=Math.min(nz-1,z0+1),tx=x-x0,ty=y-y0,tz=z-z0;const c00=lerp(v.huAt(x0,y0,z0),v.huAt(x1,y0,z0),tx),c10=lerp(v.huAt(x0,y1,z0),v.huAt(x1,y1,z0),tx),c01=lerp(v.huAt(x0,y0,z1),v.huAt(x1,y0,z1),tx),c11=lerp(v.huAt(x0,y1,z1),v.huAt(x1,y1,z1),tx);return lerp(lerp(c00,c10,ty),lerp(c01,c11,ty),tz)}
function render(width:number,height:number,scale:number,getHu:(x:number,y:number)=>number,w:CtWindow){const ow=Math.max(width,Math.round(width*scale)),oh=Math.max(height,Math.round(height*scale)),pixels=new Uint8ClampedArray(ow*oh);for(let row=0;row<oh;row++){const y=(row+.5)*height/oh-.5;for(let col=0;col<ow;col++){const x=(col+.5)*width/ow-.5;pixels[row*ow+col]=windowHu(getHu(x,y),w)}}return{width:ow,height:oh,pixels}}
// Educational interpolation improves display continuity for coarse source voxels without inventing new anatomical structures.
export function axialSlice(v:TeachingVolume,index:number,w:CtWindow){const[nx,ny,nz]=v.source.manifest.dimensions,displayIndex=Math.max(0,Math.min(nz-1,Math.round(index))),z=nz-1-displayIndex,r=render(nx,ny,2,(col,row)=>sample(v,nx-1-col,ny-1-row,z),w);return{...r,index:displayIndex}}
export function coronalSlice(v:TeachingVolume,index:number,w:CtWindow){const[nx,ny,nz]=v.source.manifest.dimensions,y=Math.max(0,Math.min(ny-1,Math.round(index))),r=render(nx,nz,2,(col,row)=>sample(v,nx-1-col,y,nz-1-row),w);return{...r,index:y}}
export function sagittalSlice(v:TeachingVolume,index:number,w:CtWindow){const[nx,ny,nz]=v.source.manifest.dimensions,x=Math.max(0,Math.min(nx-1,Math.round(index))),r=render(ny,nz,2,(col,row)=>sample(v,x,ny-1-col,nz-1-row),w);return{...r,index:x}}
export function ctSlice(v:TeachingVolume,plane:CtPlane,index:number,w:CtWindow){return plane==='axial'?axialSlice(v,index,w):plane==='coronal'?coronalSlice(v,index,w):sagittalSlice(v,index,w)}
export function planeLength(v:TeachingVolume,plane:CtPlane){const[nx,ny,nz]=v.source.manifest.dimensions;return plane==='axial'?nz:plane==='coronal'?ny:nx}
