import type{TeachingVolume}from'./teaching-volume';import{radiographImage,renderRadiographWhenMounted}from'./radiograph-image';
export type ProjectionView='AP'|'PA'|'LATERAL';
export interface CollimatorEdges{left:number;right:number;top:number;bottom:number}
export interface ProjectionOptions{axis?:'x'|'y'|'z';view?:ProjectionView;stepVoxels?:number;kVp:number;mAs:number;sidCm?:number;rotationDeg?:number;fieldPercent?:number;collimation?:Partial<CollimatorEdges>;centreXPercent?:number;centreYPercent?:number;tubeAngleDeg?:number;seed?:number;detectorWidthCm?:number;detectorHeightCm?:number}
function attenuation(hu:number,kVp:number){if(hu<=-950)return .00002;const density=Math.max(.02,(hu+1000)/1000),e=Math.max(.45,Math.min(1.6,kVp/100));let compton=.012,photo=.003;if(hu<-500){compton=.004;photo=.0005}else if(hu<-80){compton=.010;photo=.0018}else if(hu>250){compton=.016;photo=.022*Math.min(2.2,1+hu/1200)}return Math.max(.00001,density*(compton/e+photo/Math.pow(e,3)))}
function rng(seed:number){let s=seed>>>0;return()=>{s=(1664525*s+1013904223)>>>0;return s/4294967296}}
function sample(v:TeachingVolume,x:number,y:number,z:number){const[nx,ny,nz]=v.source.manifest.dimensions,xi=Math.round(x),yi=Math.round(y),zi=Math.round(z);if(xi<0||yi<0||zi<0||xi>=nx||yi>=ny||zi>=nz)return-1000;return v.huAt(xi,yi,zi)}
export function projectVolume(v:TeachingVolume,o:ProjectionOptions){
 const[nx,ny,nz]=v.source.manifest.dimensions,[sx,sy,sz]=v.source.manifest.spacingMm,view=o.view??(o.axis==='x'?'LATERAL':'AP'),lateral=view==='LATERAL';
 const detW=(o.detectorWidthCm??35)*10,detH=(o.detectorHeightCm??43)*10,pixelMm=1.5,width=Math.max(160,Math.min(512,Math.round(detW/pixelMm))),height=Math.max(180,Math.min(640,Math.round(detH/pixelMm))),raw=new Float32Array(width*height),mask=new Uint8Array(width*height),random=rng(o.seed??1),step=Math.max(1,o.stepVoxels??1),sidMm=Math.max(900,(o.sidCm??180)*10),inverseSquare=Math.pow(1800/sidMm,2),kvOutput=Math.pow(Math.max(40,o.kVp)/100,2),incidentPhotons=Math.max(50,o.mAs*4200*kvOutput*inverseSquare),angle=(o.rotationDeg??0)*Math.PI/180,c=Math.cos(angle),s=Math.sin(angle),cx=(nx-1)/2,cy=(ny-1)/2,cz=(nz-1)/2,depthMm=lateral?nx*sx:ny*sy,sourceDistanceVox=(sidMm-depthMm/2)/(lateral?sx:sy),detectorDistanceVox=(depthMm/2)/(lateral?sx:sy),field=Math.max(.05,Math.min(1,(o.fieldPercent??100)/100)),fallback=(1-field)*50,edges={left:o.collimation?.left??fallback,right:o.collimation?.right??fallback,top:o.collimation?.top??fallback,bottom:o.collimation?.bottom??fallback},centreX=(o.centreXPercent??0)/100*width,centreY=(o.centreYPercent??0)/100*height,tube=Math.tan((o.tubeAngleDeg??0)*Math.PI/180),fieldArea=Math.max(.04,(1-(edges.left+edges.right)/100)*(1-(edges.top+edges.bottom)/100)),scatterFraction=.02+.16*Math.sqrt(fieldArea);let raySamples=0;
 for(let j=0;j<height;j++)for(let i=0;i<width;i++){
  const px=(i+.5)/width*100,py=(j+.5)/height*100,idx=j*width+i;if(px<edges.left||px>100-edges.right||py<edges.top||py>100-edges.bottom)continue;
  const u=((i-centreX+.5)/width-.5)*detW/(lateral?sy:sx),vz=((j-centreY+.5)/height-.5)*detH/sz;let src:[number,number,number],det:[number,number,number];
  if(lateral){src=[cx-sourceDistanceVox,cy,cz-sourceDistanceVox*tube];det=[cx+detectorDistanceVox,cy+u,cz+vz]}else{const pa=view==='PA',sdir=pa?1:-1;src=[cx,cy+sdir*sourceDistanceVox,cz-sourceDistanceVox*tube];det=[cx+u,cy-sdir*detectorDistanceVox,cz+vz]}
  const dx=det[0]-src[0],dy=det[1]-src[1],dz=det[2]-src[2],distance=Math.sqrt(dx*dx+dy*dy+dz*dz),samples=Math.max(1,Math.ceil(distance/step));let sum=0,count=0;
  for(let q=0;q<=samples;q++){const t=q/samples,x=src[0]+dx*t,y=src[1]+dy*t,z=src[2]+dz*t,rx=c*(x-cx)-s*(y-cy)+cx,ry=s*(x-cx)+c*(y-cy)+cy,hu=sample(v,rx,ry,z);if(hu>-999){const mm=step*Math.sqrt((sx*sx+sy*sy+sz*sz)/3);sum+=attenuation(hu,o.kVp)*mm;count++}}
  raySamples=Math.max(raySamples,count);if(!count)continue;const primary=Math.exp(-sum),scatter=scatterFraction*primary*Math.min(1,count/120),expected=Math.max(.5,incidentPhotons*(primary+scatter)),noise=(random()+random()+random()+random()-2)*Math.sqrt(expected),detected=Math.max(.25,expected+noise);raw[idx]=detected;mask[idx]=1;
 }
 // Fixed detector response: unlike per-image min/max normalisation this deliberately preserves exposure.
 // More mAs/kVp output or shorter SID increases receptor signal (darker image); low photon counts increase quantum mottle.
 const reference=8500;const out=new Uint8ClampedArray(width*height);for(let i=0;i<out.length;i++){if(!mask[i]){out[i]=8;continue}const signal=Math.log1p(raw[i])/Math.log1p(reference),density=Math.max(0,Math.min(1.15,signal));out[i]=Math.round(248-Math.min(238,density*205))}
 const flipped=new Uint8ClampedArray(out.length);for(let y=0;y<height;y++)flipped.set(out.subarray((height-1-y)*width,(height-y)*width),y*width);const image=radiographImage(width,height,flipped);renderRadiographWhenMounted(image);return{width,height,pixels:flipped,raySamples,exposure:{incidentPhotons,inverseSquare,fieldArea,scatterFraction}};
}
