import type{TeachingVolume}from'./teaching-volume';
export type ProjectionView='AP'|'PA'|'LATERAL';
export interface ProjectionOptions{axis?:'x'|'y'|'z';view?:ProjectionView;stepVoxels?:number;kVp:number;mAs:number;sidCm?:number;rotationDeg?:number;fieldPercent?:number;seed?:number}
function attenuation(hu:number,kVp:number){const density=Math.max(0,(hu+1000)/1000);const energy=Math.max(.55,Math.min(1.45,kVp/100));return density*.018/energy}
function rng(seed:number){let s=seed>>>0;return()=>{s=(1664525*s+1013904223)>>>0;return s/4294967296}}
function sample(v:TeachingVolume,x:number,y:number,z:number){const[nx,ny,nz]=v.source.manifest.dimensions;const xi=Math.round(x),yi=Math.round(y),zi=Math.round(z);if(xi<0||yi<0||zi<0||xi>=nx||yi>=ny||zi>=nz)return-1000;return v.huAt(xi,yi,zi)}
export function projectVolume(v:TeachingVolume,o:ProjectionOptions){const[nx,ny,nz]=v.source.manifest.dimensions;const view=o.view??(o.axis==='x'?'LATERAL':'AP'),lateral=view==='LATERAL',width=lateral?ny:nx,height=nz,out=new Uint8ClampedArray(width*height),random=rng(o.seed??1);const step=Math.max(1,o.stepVoxels??1),photons=Math.max(20,o.mAs*2500),angle=(o.rotationDeg??0)*Math.PI/180,c=Math.cos(angle),s=Math.sin(angle),cx=(nx-1)/2,cy=(ny-1)/2,field=Math.max(.05,Math.min(1,(o.fieldPercent??100)/100)),halfW=width*field/2,halfH=height*field/2,sidScale=Math.max(.75,Math.min(1.25,(o.sidCm??180)/180));let raySamples=0;
for(let j=0;j<height;j++)for(let i=0;i<width;i++){const inside=Math.abs(i-(width-1)/2)<=halfW&&Math.abs(j-(height-1)/2)<=halfH;if(!inside){out[j*width+i]=0;continue}let sum=0,count=0;if(lateral){for(let x=0;x<nx;x+=step){const dx=x-cx,dy=i-cy,rx=c*dx-s*dy+cx,ry=s*dx+c*dy+cy;sum+=attenuation(sample(v,rx,ry,j),o.kVp);count++}}else{for(let y=0;y<ny;y+=step){const dx=i-cx,dy=y-cy,rx=c*dx-s*dy+cx,ry=s*dx+c*dy+cy;sum+=attenuation(sample(v,rx,ry,j),o.kVp);count++}}raySamples=Math.max(raySamples,count);const primary=Math.exp(-sum*step/sidScale),expected=Math.max(1,photons*primary),noise=(random()+random()+random()+random()-2)*Math.sqrt(expected),measured=Math.max(1,expected+noise),optical=-Math.log(measured/photons);out[j*width+i]=Math.max(0,Math.min(255,Math.round(255-optical*115)))}
// Source z is inferior->superior; detector display is head-up.
const flipped=new Uint8ClampedArray(out.length);for(let y=0;y<height;y++)flipped.set(out.subarray((height-1-y)*width,(height-y)*width),y*width);return{width,height,pixels:flipped,raySamples}}
