import{RADIOGRAPHIC_POSITIONS,type RadiographicPosition}from'./radiographic-positions';

export interface ExposureReferenceEntry{
 id:string;region:string;projection:string;title:string;
 centringPoint:string;areaOfInterest:string;expectedAnatomy:string[];
 rotationChecks:string[];qualityChecks:string[];positioning:string[];
 exposure:{kVp:number;mAs:number;sidCm:number;grid:boolean;aec:boolean};
 positionImage?:string;collimationImage?:string;sourceNote:string;
}

type Guidance={centringPoint:string;areaOfInterest:string;expectedAnatomy:string[];rotationChecks:string[];qualityChecks:string[]};

const generic=(p:RadiographicPosition):Guidance=>({
 centringPoint:'Centre to the middle of the requested anatomy using palpable external landmarks.',
 areaOfInterest:`Include the complete ${p.region.toLowerCase()} required for the projection, with appropriate adjacent joints where relevant.`,
 expectedAnatomy:[p.region,`${p.projection} relationship of the requested anatomy`,'Relevant joint spaces and adjacent soft tissues'],
 rotationChecks:['Compare paired cortices/joint spaces for symmetry appropriate to the projection.','Confirm the intended AP/PA/lateral/oblique relationship has been achieved.'],
 qualityChecks:['Required anatomy is included without avoidable cut-off.','Collimation is close to the anatomy of interest.','No avoidable motion artefact.','Exposure permits cortical and relevant soft-tissue detail.']
});

const G:Record<string,Partial<Guidance>>={
 'chest-pa-erect':{centringPoint:'MSP at approximately T7, around the inferior angle of the scapulae.',areaOfInterest:'Both lungs from apices to costophrenic angles, including lateral chest margins, hila and cardiac silhouette.',expectedAnatomy:['Both lung fields','Apices and costophrenic angles','Trachea and hila','Cardiac and mediastinal contours','Ribs, clavicles and thoracic spine'],rotationChecks:['Medial clavicular heads should be approximately equidistant from the thoracic spinous processes.','Thoracic cage should be symmetric without one hemithorax appearing markedly wider.'],qualityChecks:['Scapulae projected largely clear of the lungs.','Adequate inspiration, normally demonstrated by good lung expansion.','Apices and both costophrenic angles included.','Thoracic vertebrae are faintly visible through the heart/mediastinum without overexposure.']},
 'chest-ap':{centringPoint:'MSP at approximately T7.',areaOfInterest:'Entire thorax including both apices and costophrenic angles.',expectedAnatomy:['Both lungs','Heart and mediastinum','Hila','Diaphragms and costophrenic angles'],rotationChecks:['Medial clavicles should be approximately equidistant from the spine.','Check thoracic symmetry.']},
 'chest-lateral-erect':{centringPoint:'Mid-coronal plane at approximately T7.',areaOfInterest:'Entire lungs from apices to posterior costophrenic angles.',expectedAnatomy:['Retrosternal clear space','Heart','Hila','Posterior ribs','Costophrenic angles'],rotationChecks:['Posterior ribs should be close to superimposed.','Sternum should be seen in profile.']},
 'abdomen-ap-supine':{centringPoint:'MSP at the level of the iliac crests.',areaOfInterest:'Abdomen from the upper abdomen to the symphysis pubis, adjusted to the clinical indication.',expectedAnatomy:['Bowel gas pattern','Renal outlines when visible','Psoas margins','Lumbar spine','Pelvic structures'],rotationChecks:['Spinous processes should be centred within vertebral bodies and iliac wings should be reasonably symmetric.']},
 'pelvis-ap':{centringPoint:'MSP midway between the ASIS and pubic symphysis.',areaOfInterest:'Entire pelvis including iliac crests, acetabula, pubic symphysis and proximal femora.',expectedAnatomy:['Iliac wings','Acetabula','Pubic rami','Sacrum and SI joints','Femoral heads/necks and proximal femora'],rotationChecks:['Obturator foramina and iliac wings should be approximately symmetric.','Sacrum/coccyx should align with the pubic symphysis.']},
 'cspine-ap':{centringPoint:'Midline at C4, approximately the level of the thyroid cartilage.',areaOfInterest:'C3 to T1 where possible, including lateral margins of the cervical spine.',expectedAnatomy:['Cervical vertebral bodies','Intervertebral spaces','Uncovertebral regions','Upper thoracic junction'],rotationChecks:['Spinous processes should be central within vertebral bodies.','Mandible should be symmetric across the upper cervical spine.']},
 'cspine-lateral':{centringPoint:'C4, in the coronal plane through the cervical spine.',areaOfInterest:'Skull base through C7/T1, including prevertebral soft tissues.',expectedAnatomy:['C1-C7 vertebrae','C7/T1 junction','Prevertebral soft tissues','Facet/articular pillars'],rotationChecks:['Posterior vertebral body margins and articular pillars should be near superimposed.']},
 'cspine-odontoid':{centringPoint:'Through the open mouth to C1/C2.',areaOfInterest:'Dens, lateral masses of C1 and C2 articulation.',expectedAnatomy:['Dens','C1 lateral masses','C2 body'],rotationChecks:['Lateral masses of C1 should be symmetric around the dens when positioning is correct.']},
 'facial-om':{centringPoint:'Beam exits at the lower orbital margin.',areaOfInterest:'Facial bones and maxillary sinuses with both orbital floors.',expectedAnatomy:['Maxillary sinuses','Orbital rims/floors','Zygomatic bones','Nasal region'],rotationChecks:['Petrous ridges and facial structures should be symmetric.']},
 'facial-om30':{centringPoint:'Beam exits at the lower orbital margin with the prescribed caudal angle.',areaOfInterest:'Facial bones with emphasis on orbital floors and maxillary region.',expectedAnatomy:['Orbits','Maxillary sinuses','Zygomatic arches','Facial skeleton'],rotationChecks:['Facial structures should remain symmetric without lateral rotation.']},
 'lspine-ap':{centringPoint:'MSP at L3, around the level of the lower costal margin.',areaOfInterest:'T12/L1 junction through the sacrum, including transverse processes and SI joints.',expectedAnatomy:['L1-L5 vertebrae','Intervertebral disc spaces','Transverse processes','Sacrum and SI joints'],rotationChecks:['Spinous processes should be central and pedicles symmetric.']},
 'lspine-lateral':{centringPoint:'Approximately 10 cm anterior to L3 at the lower costal margin.',areaOfInterest:'T12/L1 through L5/S1 with posterior elements and sacrum.',expectedAnatomy:['Lumbar vertebral bodies','Disc spaces','Posterior elements','Lumbosacral junction'],rotationChecks:['Posterior vertebral body margins should be close to superimposed.']},
 'tspine-ap':{centringPoint:'MSP midway between the sternal notch and xiphoid process.',areaOfInterest:'Thoracic spine from C7/T1 to T12/L1.',expectedAnatomy:['T1-T12 vertebrae','Pedicles','Intervertebral spaces','Adjacent rib heads'],rotationChecks:['Spinous processes should be central and pedicles reasonably symmetric.']},
 'tspine-lateral':{centringPoint:'Approximately 5 cm anterior to T6 at axillary level.',areaOfInterest:'Thoracic spine from C7/T1 to T12/L1.',expectedAnatomy:['Thoracic vertebral bodies','Disc spaces','Posterior ribs','Cervicothoracic and thoracolumbar junctions'],rotationChecks:['Posterior vertebral body margins should be close to superimposed.']},
 'shoulder-ap':{centringPoint:'Approximately 2.5 cm inferior to the coracoid process.',areaOfInterest:'Entire glenohumeral joint, proximal humerus, lateral clavicle and scapular region.',expectedAnatomy:['Humeral head','Glenoid','Acromion','Distal clavicle'],rotationChecks:['Assess humeral tuberosity profile and glenohumeral relationship for the intended AP position.']},
 'humerus-ap':{centringPoint:'Midshaft of the humerus.',areaOfInterest:'Entire humerus including shoulder and elbow joints.',expectedAnatomy:['Humeral shaft','Proximal humerus','Distal humerus','Shoulder and elbow joints'],rotationChecks:['Epicondyles should be approximately parallel to the receptor for a true AP.']},
 'humerus-lateral':{centringPoint:'Midshaft of the humerus.',areaOfInterest:'Entire humerus including shoulder and elbow.',expectedAnatomy:['Humeral shaft','Proximal and distal humerus'],rotationChecks:['Epicondyles should be approximately perpendicular to the receptor for a lateral.']},
 'elbow-ap':{centringPoint:'Through the elbow joint space, approximately 2.5 cm distal to the midpoint between the medial and lateral epicondyles.',areaOfInterest:'Distal one-third of humerus, elbow joint, proximal one-third of radius and ulna, and the medial/lateral soft-tissue margins.',expectedAnatomy:['Distal humerus','Elbow joint space','Radial head and neck','Proximal ulna and olecranon','Relevant soft tissues'],rotationChecks:['Medial and lateral epicondyles should be equidistant from the image receptor.','The arm must be fully supinated with no unintended rotation.']},
 'elbow-lateral':{centringPoint:'To the lateral epicondyle with the elbow joint centred on the receptor.',areaOfInterest:'Distal one-third of humerus, elbow joint, proximal one-third of radius and ulna, and the lateral soft-tissue margins.',expectedAnatomy:['Distal humerus','Olecranon in profile','Radial head','Proximal radius and ulna','Elbow fat pads when visible'],rotationChecks:['Humeral epicondyles should be superimposed or very nearly superimposed.','The elbow should remain flexed to 90 degrees with the palm vertical and the humerus, elbow and wrist on the same horizontal plane.']},
 'forearm-ap':{centringPoint:'Mid-forearm.',areaOfInterest:'Entire radius and ulna including wrist and elbow joints.',expectedAnatomy:['Radius','Ulna','Wrist joint','Elbow joint'],rotationChecks:['Radius and ulna should be demonstrated in the intended AP relationship.']},
 'forearm-lateral':{centringPoint:'Mid-forearm.',areaOfInterest:'Entire radius and ulna including wrist and elbow.',expectedAnatomy:['Radius','Ulna','Wrist','Elbow'],rotationChecks:['Distal radius/ulna and elbow should demonstrate lateral superimposition appropriate to the projection.']},
 'wrist-pa':{centringPoint:'Midcarpal region.',areaOfInterest:'Distal radius/ulna, carpal bones and proximal metacarpals.',expectedAnatomy:['Distal radius and ulna','Carpal bones','Proximal metacarpals'],rotationChecks:['Carpal alignment should be symmetric without obvious obliquity.']},
 'wrist-lateral':{centringPoint:'Midcarpal region.',areaOfInterest:'Distal radius/ulna, carpal bones and proximal metacarpals.',expectedAnatomy:['Distal radius/ulna','Carpal bones','Proximal metacarpals'],rotationChecks:['Distal radius and ulna should be near superimposed for a true lateral.']},
 'hand-pa':{centringPoint:'Third MCP joint.',areaOfInterest:'Entire hand from distal radius/ulna to fingertips.',expectedAnatomy:['Phalanges','Metacarpals','Carpal bones','Distal radius/ulna'],rotationChecks:['Phalangeal/metacarpal concavities should be symmetric with minimal rotation.']},
 'hand-oblique':{centringPoint:'Third MCP joint.',areaOfInterest:'Entire hand and wrist.',expectedAnatomy:['Phalanges','Metacarpals','Carpal bones'],rotationChecks:['Approximately 45° obliquity should separate metacarpal heads appropriately.']},
 'hip-ap':{centringPoint:'Femoral neck, approximately 2.5 cm distal to the midpoint of the line between ASIS and pubic symphysis.',areaOfInterest:'Hip joint, acetabulum and proximal femur.',expectedAnatomy:['Acetabulum','Femoral head/neck','Greater and lesser trochanters','Proximal femur'],rotationChecks:['Femoral neck should not be foreshortened and lesser trochanter profile should match the intended rotation.']},
 'femur-ap':{centringPoint:'Mid-femoral shaft.',areaOfInterest:'Entire femur including hip and knee joints where possible.',expectedAnatomy:['Femoral shaft','Hip joint','Knee joint'],rotationChecks:['Femoral condyles should be symmetric for AP positioning.']},
 'femur-lateral':{centringPoint:'Mid-femoral shaft.',areaOfInterest:'Entire femur including adjacent joints.',expectedAnatomy:['Femoral shaft','Hip and knee relationship'],rotationChecks:['Femoral condyles should be near superimposed at the knee for a lateral.']},
 'knee-ap':{centringPoint:'Approximately 2.5 cm distal to the apex of the patella in the midline.',areaOfInterest:'Distal femur, proximal tibia/fibula and complete knee joint.',expectedAnatomy:['Distal femur','Tibial plateau','Fibular head','Patella','Knee joint'],rotationChecks:['Femoral condyles should be symmetric and tibial spines centred.']},
 'knee-lateral':{centringPoint:'Approximately 2.5 cm distal to the medial epicondyle.',areaOfInterest:'Distal femur, patella and proximal tibia/fibula.',expectedAnatomy:['Femoral condyles','Patella','Tibial plateau','Fibular head'],rotationChecks:['Posterior femoral condyles should be near superimposed.']},
 'tibfib-ap':{centringPoint:'Midpoint of the tibia/fibula.',areaOfInterest:'Entire tibia and fibula including knee and ankle joints.',expectedAnatomy:['Tibia','Fibula','Knee joint','Ankle joint'],rotationChecks:['Tibia/fibula relationship should correspond to AP positioning.']},
 'tibfib-lateral':{centringPoint:'Midpoint of the tibia/fibula.',areaOfInterest:'Entire tibia/fibula including knee and ankle.',expectedAnatomy:['Tibia','Fibula','Knee','Ankle'],rotationChecks:['Distal tibia/fibula should be near superimposed in the lateral projection.']},
 'ankle-ap':{centringPoint:'Midway between the malleoli.',areaOfInterest:'Distal tibia/fibula, talus and ankle mortise.',expectedAnatomy:['Distal tibia','Distal fibula','Talus','Ankle joint'],rotationChecks:['Malleoli should have the expected AP relationship without excessive rotation.']},
 'ankle-mortise':{centringPoint:'Midway between the malleoli.',areaOfInterest:'Entire ankle mortise and distal tibia/fibula.',expectedAnatomy:['Tibiotalar joint','Medial and lateral malleoli','Talus'],rotationChecks:['Mortise should be open with minimal tibiofibular overlap appropriate to the view.']},
 'ankle-lateral':{centringPoint:'Medial malleolus.',areaOfInterest:'Distal tibia/fibula, talus, calcaneus and proximal midfoot.',expectedAnatomy:['Talus','Calcaneus','Distal tibia/fibula','Ankle joint'],rotationChecks:['Talar domes should be near superimposed.']},
 'foot-dp':{centringPoint:'Base of the third metatarsal.',areaOfInterest:'Entire foot from calcaneus to distal phalanges.',expectedAnatomy:['Tarsals','Metatarsals','Phalanges'],rotationChecks:['Metatarsal bases should show the expected DP relationships without unwanted obliquity.']},
 'foot-oblique':{centringPoint:'Base of the third metatarsal.',areaOfInterest:'Entire foot, especially lateral tarsals and metatarsal bases.',expectedAnatomy:['Tarsals','Metatarsals','Phalanges'],rotationChecks:['Cuboid, sinus tarsi and metatarsal bases should demonstrate appropriate obliquity.']},
 'foot-lateral':{centringPoint:'Base of the third metatarsal.',areaOfInterest:'Entire foot including calcaneus and distal phalanges.',expectedAnatomy:['Calcaneus','Talus','Tarsals','Metatarsals','Phalanges'],rotationChecks:['Metatarsals should be largely superimposed and the ankle should be lateral.']}
};

function build(p:RadiographicPosition):ExposureReferenceEntry{
 const g={...generic(p),...(G[p.id]??{})} as Guidance;
 const images=p.id==='elbow-ap'?{positionImage:'/reference/elbow-ap-position.svg',collimationImage:'/reference/elbow-ap-collimation.svg'}:p.id==='elbow-lateral'?{positionImage:'/reference/elbow-lateral-position.svg',collimationImage:'/reference/elbow-lateral-collimation.svg'}:{};
 return{id:p.id,region:p.region,projection:p.projection,title:`${p.region} · ${p.projection}`,centringPoint:g.centringPoint,areaOfInterest:g.areaOfInterest,expectedAnatomy:g.expectedAnatomy,rotationChecks:g.rotationChecks,qualityChecks:g.qualityChecks,positioning:p.patientInstructions.length?p.patientInstructions:p.pose.notes.length?p.pose.notes:['Position the patient according to the selected projection and keep the required anatomy close to the receptor.'],exposure:{kVp:p.exposure.kVp,mAs:p.exposure.mAs,sidCm:p.exposure.sidCm,grid:!!p.exposure.grid,aec:!!p.exposure.aec},...images,sourceNote:'Positioning criteria are paraphrased from standard radiographic positioning guidance, including Clark’s Positioning in Radiography. Exposure factors are Bucky Lab departmental examples for an average adult and are not a universal clinical technique chart.'};
}
export const EXPOSURE_REFERENCE_LIBRARY=RADIOGRAPHIC_POSITIONS.map(build);
export function exposureReference(id:string){return EXPOSURE_REFERENCE_LIBRARY.find(x=>x.id===id)??EXPOSURE_REFERENCE_LIBRARY[0]}
