export type Modality='X-ray'|'CT';
export type AnnotationKind='anatomy'|'pathology'|'landmark';
export interface ImagePoint{x:number;y:number}
export interface LearningAnnotation{id:string;modality:Modality;region:string;projectionOrPlane:string;kind:AnnotationKind;label:string;description:string;points:ImagePoint[];sliceRange?:[number,number]}
export interface PathologyLesson{id:string;title:string;modalities:Modality[];regions:string[];appearance:string[];lookFor:string[];bestViews:string[];pitfalls:string[];differentials:string[];references:string[]}
export const LEARNING_ANNOTATIONS:LearningAnnotation[]=[
{id:'chest-trachea',modality:'X-ray',region:'Chest',projectionOrPlane:'PA',kind:'anatomy',label:'Trachea',description:'Central air column. Assess position before attributing mediastinal shift.',points:[{x:.5,y:.18}]},
{id:'chest-right-hilum',modality:'X-ray',region:'Chest',projectionOrPlane:'PA',kind:'anatomy',label:'Right hilum',description:'Predominantly pulmonary vascular structures; normally lower than the left hilum.',points:[{x:.43,y:.42}]},
{id:'chest-left-hilum',modality:'X-ray',region:'Chest',projectionOrPlane:'PA',kind:'anatomy',label:'Left hilum',description:'Predominantly pulmonary vascular structures; normally slightly higher than the right.',points:[{x:.57,y:.39}]},
{id:'chest-cpa-right',modality:'X-ray',region:'Chest',projectionOrPlane:'PA',kind:'landmark',label:'Right costophrenic angle',description:'Should be included and normally appears sharp on an adequate PA chest radiograph.',points:[{x:.31,y:.82}]},
{id:'chest-cpa-left',modality:'X-ray',region:'Chest',projectionOrPlane:'PA',kind:'landmark',label:'Left costophrenic angle',description:'Inspect for blunting, pleural fluid and completeness of coverage.',points:[{x:.69,y:.82}]},
{id:'ct-liver',modality:'CT',region:'Abdomen',projectionOrPlane:'axial',kind:'anatomy',label:'Liver',description:'Right upper abdominal solid organ. Attenuation and enhancement depend on phase.',points:[{x:.34,y:.48}]},
{id:'ct-spleen',modality:'CT',region:'Abdomen',projectionOrPlane:'axial',kind:'anatomy',label:'Spleen',description:'Left upper abdominal solid organ; compare enhancement and attenuation with adjacent structures.',points:[{x:.7,y:.43}]},
{id:'ct-aorta',modality:'CT',region:'CAP',projectionOrPlane:'axial',kind:'anatomy',label:'Aorta',description:'Major arterial vessel anterior/left of the vertebral body in the abdomen; enhancement depends on contrast phase.',points:[{x:.53,y:.58}]}
];
export const PATHOLOGY_LESSONS:PathologyLesson[]=[
{id:'pneumothorax',title:'Pneumothorax',modalities:['X-ray','CT'],regions:['Chest'],appearance:['Visceral pleural line separated from the chest wall','Absent peripheral lung markings beyond the pleural line','On CT, pleural gas separates visceral from parietal pleura'],lookFor:['Trace the pleural edge, especially apices and lateral chest','Compare peripheral vascular markings side-to-side','Assess for mediastinal displacement when tension is suspected'],bestViews:['Erect PA chest when clinically appropriate','CT lung windows for small/occult pneumothorax'],pitfalls:['Skin folds and scapular margins can mimic a pleural line','Do not diagnose from hyperlucency alone'],differentials:['Skin fold','Bullous disease','Large pulmonary cyst'],references:['Bucky Lab educational synthesis; verify against current radiology teaching references and local practice.']},
{id:'pleural-effusion',title:'Pleural effusion',modalities:['X-ray','CT'],regions:['Chest'],appearance:['Blunting of the costophrenic angle','Dependent homogeneous opacity, often with a meniscus','CT demonstrates dependent pleural fluid'],lookFor:['Inspect both costophrenic angles','Assess diaphragmatic contour and dependent pleural space','On CT, distinguish pleural fluid from adjacent atelectatic lung'],bestViews:['PA and lateral chest','Axial/coronal CT soft-tissue windows'],pitfalls:['Subpulmonic fluid can alter apparent hemidiaphragm position','Supine radiographs may show diffuse veiling rather than a classic meniscus'],differentials:['Pleural thickening','Basal consolidation','Elevated hemidiaphragm'],references:['Bucky Lab educational synthesis; verify against current radiology teaching references and local practice.']},
{id:'intracranial-haemorrhage',title:'Acute intracranial haemorrhage',modalities:['CT'],regions:['Head'],appearance:['Acute blood is typically hyperattenuating relative to brain on non-contrast CT','Distribution and shape help localise the compartment'],lookFor:['Review brain windows systematically','Check sulci, ventricles, basal cisterns and extra-axial spaces','Assess mass effect, midline shift and hydrocephalus'],bestViews:['Non-contrast head CT','Axial review with coronal/sagittal reformats when available'],pitfalls:['Calcification and contrast can be hyperattenuating','Beam-hardening can mimic abnormal density near skull base'],differentials:['Calcification','Contrast staining','Hyperdense tumour'],references:['Bucky Lab educational synthesis; verify against current radiology teaching references and local practice.']}
];
export function annotationsFor(modality:Modality,region:string,view:string,slice?:number){return LEARNING_ANNOTATIONS.filter(a=>a.modality===modality&&a.region.toLowerCase()===region.toLowerCase()&&a.projectionOrPlane.toLowerCase()===view.toLowerCase()&&(!a.sliceRange||slice===undefined||(slice>=a.sliceRange[0]&&slice<=a.sliceRange[1])))}
export function pathologyLesson(id:string){return PATHOLOGY_LESSONS.find(p=>p.id===id)}
