export type LearningTopic='anatomy'|'pathology'|'physics'|'positioning'|'exposure'|'room';
export interface LearningModule{id:string;topic:LearningTopic;title:string;summary:string;points:string[]}
export const LEARNING_MODULES:LearningModule[]=[
{id:'anatomy-systematic',topic:'anatomy',title:'Radiographic anatomy',summary:'Recognise normal structures on acquired radiographs and processed CT images.',points:['Trace cortical margins and joint relationships systematically.','Relate projected anatomy to the selected examination and projection.','Use post-acquisition labels to check structures against the image rather than the positioning model.']},
{id:'pathology-search',topic:'pathology',title:'Pathology search strategy',summary:'Build a repeatable visual search before revealing teaching guidance.',points:['Inspect the complete image before focusing on the suspected abnormality.','Describe location, morphology and effect on adjacent structures.','Use the pathology overlay only after forming an initial interpretation.']},
{id:'xray-physics',topic:'physics',title:'X-ray production and image formation',summary:'Connect tube settings, attenuation, scatter and geometry to the resulting projection.',points:['kVp changes beam energy, penetration and subject contrast.','mAs changes photon quantity and therefore receptor exposure and quantum noise.','SID changes intensity by inverse-square behaviour and influences geometric magnification.','Collimation limits irradiated volume and reduces scatter when field size is reduced.']},
{id:'positioning',topic:'positioning',title:'Positioning and projection',summary:'Understand how patient, detector and central ray relationships create the required projection.',points:['Start from the prescribed anatomical position and projection.','Use palpable or visible landmarks for centring.','Assess rotation using projection-specific symmetry or superimposition criteria.','After exposure, compare the achieved field and anatomy with the intended area of interest.']},
{id:'exposure',topic:'exposure',title:'Exposure factors',summary:'Choose sensible examination presets, then understand the consequences of changing them.',points:['Begin with the examination-specific teaching preset.','Do not judge kVp, mAs or SID independently when compensating technique.','Low photon fluence increases quantum mottle; excessive output should not be used merely to make an image look cleaner.']},
{id:'room',topic:'room',title:'Radiography room setup',summary:'Prepare the room, detector and patient pathway before exposure.',points:['Select the correct detector orientation and working SID.','Align tube, detector and patient for the requested projection.','Position equipment before bringing the patient into a difficult or unsafe posture.','Collimate and centre before exposure, then perform the post-exposure image check.']}
];
export const learningModules=(topic?:LearningTopic)=>topic?LEARNING_MODULES.filter(m=>m.topic===topic):LEARNING_MODULES;
