import type{TeachingVolume}from'./teaching-volume';
import type{LimbRegion,PatientSide}from'./limb-regions';
export interface VoxelBounds{x0:number;x1:number;y0:number;y1:number;z0:number;z1:number}
export interface LimbVolume{region:LimbRegion;side:PatientSide;bounds:VoxelBounds;dimensions:[number,number,number];huAt(x:number,y:number,z:number):number}
export interface SegmentedRegionBounds{region:LimbRegion;side:PatientSide;bounds:VoxelBounds;source:'segmentation'}
/* Limb extraction must be driven by verified segmentation-derived bounds/masks. The previous
   normalised coordinate fallback could include pelvis/abdomen and therefore produced anatomically
   misleading images. It is deliberately disabled rather than pretending that a crop is a limb. */
export function extractLimbVolume(v:TeachingVolume,region:LimbRegion,side:PatientSide,segmented?:SegmentedRegionBounds):LimbVolume|null{if(!segmented||segmented.region!==region||segmented.side!==side)return null;const[nx,ny,nz]=v.source.manifest.dimensions,b=segmented.bounds,x0=Math.max(0,Math.min(nx-1,b.x0)),x1=Math.max(x0,Math.min(nx-1,b.x1)),y0=Math.max(0,Math.min(ny-1,b.y0)),y1=Math.max(y0,Math.min(ny-1,b.y1)),z0=Math.max(0,Math.min(nz-1,b.z0)),z1=Math.max(z0,Math.min(nz-1,b.z1)),dx=x1-x0+1,dy=y1-y0+1,dz=z1-z0+1;return{region,side,bounds:{x0,x1,y0,y1,z0,z1},dimensions:[dx,dy,dz],huAt(x,y,z){if(x<0||y<0||z<0||x>=dx||y>=dy||z>=dz)return-1000;return v.huAt(x0+x,y0+y,z0+z)}}}
export function limbProjection(volume:LimbVolume,view:'AP'|'PA'|'LATERAL'='AP'){const[nx,ny,nz]=volume.dimensions,lateral=view==='LATERAL',width=lateral?ny:nx,height=nz,depth=lateral?nx:ny,pixels=new Uint8ClampedArray(width*height);for(let row=0;row<height;row++){const z=nz-1-row;for(let col=0;col<width;col++){let tissue=0,bone=0,soft=0,n=0;for(let d=0;d<depth;d+=2){const hu=lateral?volume.huAt(d,col,z):volume.huAt(col,d,z);if(hu>-650){tissue++;if(hu>180)bone++;if(hu>-200&&hu<180){soft+=hu;n++}}}pixels[row*width+col]=tissue?Math.round(Math.min(235,28+Math.min(90,tissue*3)+Math.min(100,bone*12)+(n?Math.max(0,Math.min(20,(soft/n+150)/15)):0))):6}}return{width,height,pixels}}
