export type PatientStance='erect'|'supine'|'prone'|'seated'|'decubitus';
export type DetectorOrientation='portrait'|'landscape';
export interface JointPose{flexion?:number;abduction?:number;rotation?:number}
export interface FullBodyPose{stance:PatientStance;bodyYaw:number;bodyPitch:number;bodyRoll:number;headRotation:number;headExtension:number;leftShoulder:JointPose;rightShoulder:JointPose;leftElbow:JointPose;rightElbow:JointPose;leftHip:JointPose;rightHip:JointPose;leftKnee:JointPose;rightKnee:JointPose;notes:string[]}
export interface StartingField{left:number;right:number;top:number;bottom:number;centreX:number;centreY:number}
export interface RadiographicPosition{id:string;region:string;projection:string;detector:DetectorOrientation;beam:'horizontal'|'vertical';tubeAngleDeg:number;startingField:StartingField;pose:FullBodyPose;referenceBasis:string}
const neutral=(stance:PatientStance='erect'):FullBodyPose=>({stance,bodyYaw:0,bodyPitch:0,bodyRoll:0,headRotation:0,headExtension:0,leftShoulder:{},rightShoulder:{},leftElbow:{},rightElbow:{},leftHip:{},rightHip:{},leftKnee:{},rightKnee:{},notes:[]});
export const RADIOGRAPHIC_POSITIONS:RadiographicPosition[]=[
{id:'chest-pa-erect',region:'Chest',projection:'PA erect',detector:'portrait',beam:'horizontal',tubeAngleDeg:0,startingField:{left:18,right:18,top:18,bottom:39,centreX:0,centreY:18},pose:{...neutral('erect'),leftShoulder:{rotation:20},rightShoulder:{rotation:20},notes:['Anterior chest against detector','Shoulders depressed and rolled forward','Chin elevated clear of lung apices']},referenceBasis:'Clark-style PA chest positioning'},
{id:'chest-lateral-erect',region:'Chest',projection:'Lateral erect',detector:'portrait',beam:'horizontal',tubeAngleDeg:0,startingField:{left:27,right:27,top:18,bottom:39,centreX:0,centreY:18},pose:{...neutral('erect'),bodyYaw:90,leftShoulder:{flexion:180},rightShoulder:{flexion:180},leftElbow:{flexion:90},rightElbow:{flexion:90},notes:['Side against detector','Arms raised clear of thorax']},referenceBasis:'Clark-style lateral chest positioning'},
{id:'abdomen-ap-supine',region:'Abdomen',projection:'AP supine',detector:'portrait',beam:'vertical',tubeAngleDeg:0,startingField:{left:19,right:19,top:38,bottom:22,centreX:0,centreY:-12},pose:{...neutral('supine'),notes:['Median sagittal plane perpendicular to detector','Arms moved clear of abdomen']},referenceBasis:'Clark-style AP supine abdomen'},
{id:'pelvis-ap',region:'Pelvis',projection:'AP pelvis',detector:'landscape',beam:'vertical',tubeAngleDeg:0,startingField:{left:17,right:17,top:48,bottom:12,centreX:0,centreY:-22},pose:{...neutral('supine'),leftHip:{rotation:-15},rightHip:{rotation:15},notes:['Lower limbs internally rotated when clinically appropriate','Pelvis without rotation']},referenceBasis:'Clark-style AP pelvis'},
{id:'cspine-lateral',region:'Cervical spine',projection:'Lateral erect',detector:'portrait',beam:'horizontal',tubeAngleDeg:0,startingField:{left:32,right:32,top:4,bottom:68,centreX:0,centreY:32},pose:{...neutral('erect'),leftShoulder:{abduction:0},rightShoulder:{abduction:0},notes:['True lateral','Shoulders depressed','Chin elevated to avoid mandibular superimposition']},referenceBasis:'Clark-style lateral cervical spine'},
{id:'knee-ap',region:'Knee',projection:'AP',detector:'portrait',beam:'vertical',tubeAngleDeg:0,startingField:{left:35,right:35,top:60,bottom:5,centreX:-5,centreY:-34},pose:{...neutral('supine'),notes:['Affected limb extended','Femoral condyles aligned with detector']},referenceBasis:'Clark-style AP knee'},
{id:'knee-lateral',region:'Knee',projection:'Lateral',detector:'portrait',beam:'vertical',tubeAngleDeg:0,startingField:{left:35,right:35,top:60,bottom:5,centreX:-5,centreY:-34},pose:{...neutral('decubitus'),bodyYaw:90,leftKnee:{flexion:30},notes:['Affected side down','Knee flexed for lateral projection']},referenceBasis:'Clark-style lateral knee'}
];
export function positionsForRegion(region:string){return RADIOGRAPHIC_POSITIONS.filter(p=>p.region.toLowerCase()===region.toLowerCase())}
