export type PatientStance='erect'|'supine'|'prone'|'seated'|'decubitus';
export type DetectorOrientation='portrait'|'landscape';export type RespirationInstruction='none'|'arrested-inspiration'|'arrested-expiration';export interface JointPose{flexion?:number;abduction?:number;rotation?:number}export interface FullBodyPose{stance:PatientStance;bodyYaw:number;bodyPitch:number;bodyRoll:number;headRotation:number;headExtension:number;leftShoulder:JointPose;rightShoulder:JointPose;leftElbow:JointPose;rightElbow:JointPose;leftHip:JointPose;rightHip:JointPose;leftKnee:JointPose;rightKnee:JointPose;notes:string[]}export interface StartingField{left:number;right:number;top:number;bottom:number;centreX:number;centreY:number}export interface ExposurePreset{kVp:number;mAs:number;sidCm:number;grid?:boolean;aec?:boolean}export interface RadiographicPosition{id:string;region:string;projection:string;detector:DetectorOrientation;beam:'horizontal'|'vertical';tubeAngleDeg:number;startingField:StartingField;pose:FullBodyPose;referenceBasis:string;exposure:ExposurePreset;patientInstructions:string[];respiration:RespirationInstruction}
const neutral=(stance:PatientStance='erect'):FullBodyPose=>({stance,bodyYaw:0,bodyPitch:0,bodyRoll:0,headRotation:0,headExtension:0,leftShoulder:{},rightShoulder:{},leftElbow:{},rightElbow:{},leftHip:{},rightHip:{},leftKnee:{},rightKnee:{},notes:[]});const field=(centreY=0):StartingField=>({left:28,right:28,top:28,bottom:28,centreX:0,centreY});const pos=(id:string,region:string,projection:string,exposure:ExposurePreset,pose:FullBodyPose=neutral('supine'),detector:DetectorOrientation='portrait',beam:'horizontal'|'vertical'='vertical',tubeAngleDeg=0,startingField=field(),notes:string[]=[],patientInstructions:string[]=[],respiration:RespirationInstruction='none'):RadiographicPosition=>({id,region,projection,detector,beam,tubeAngleDeg,startingField,pose:{...pose,notes:[...pose.notes,...notes]},referenceBasis:'User-supplied positioning/exposure teaching reference; exposure factors are departmental examples, not universal technique charts.',exposure,patientInstructions,respiration});
export const RADIOGRAPHIC_POSITIONS:RadiographicPosition[]=[
pos('chest-pa-erect','Chest','PA erect',{kVp:125,mAs:2,sidCm:180,grid:true,aec:true},{...neutral('erect'),bodyYaw:180,leftShoulder:{flexion:12,abduction:-8,rotation:35},rightShoulder:{flexion:12,abduction:8,rotation:-35},leftElbow:{flexion:8},rightElbow:{flexion:8}},'portrait','horizontal',0,{left:34,right:34,top:12,bottom:60,centreX:0,centreY:0},['Anterior chest against detector','Shoulders rolled forward','Chin clear of apices'],['Stand facing the detector with your chest against it.','Raise your chin.','Roll both shoulders forward so the scapulae move laterally away from the lung fields.','Take a deep breath in, another deep breath in, and hold it.'],'arrested-inspiration'),
pos('chest-ap','Chest','AP',{kVp:96,mAs:1.6,sidCm:180,grid:false},neutral('erect'),'portrait','horizontal'),
pos('chest-lateral-erect','Chest','Lateral erect',{kVp:120,mAs:4,sidCm:180},{...neutral('erect'),bodyYaw:90,leftShoulder:{flexion:180},rightShoulder:{flexion:180}},'portrait','horizontal',0,field(),[],['Stand with your left side against the detector.','Raise both arms above your head.','Take a deep breath in and hold it.'],'arrested-inspiration'),
pos('abdomen-ap-supine','Abdomen','AP supine',{kVp:73,mAs:25,sidCm:110,grid:true},neutral('supine'),'portrait','vertical',0,field(),[],['Lie flat on your back with the midsagittal plane perpendicular to the image receptor.','Breathe out and hold your breath.'],'arrested-expiration'),
pos('pelvis-ap','Pelvis','AP',{kVp:73,mAs:25,sidCm:110,grid:true},{...neutral('supine'),leftHip:{rotation:-15},rightHip:{rotation:15}},'landscape','vertical',0,{left:12,right:12,top:18,bottom:18,centreX:0,centreY:12},['Pelvis not rotated; lower limbs internally rotated when clinically appropriate'],['Lie supine with the midsagittal plane centred and perpendicular to the receptor.','Keep the pelvis straight without rotation.','Internally rotate both lower limbs when clinically appropriate so the femoral necks are demonstrated.','Keep still for the exposure.']),
pos('cspine-ap','Cervical spine','AP',{kVp:63,mAs:6.3,sidCm:110,grid:false},{...neutral('erect'),headExtension:12},'portrait','horizontal',15,field(),['Chin raised to project occlusal plane over skull base'],['Stand erect in AP orientation.','Keep the midsagittal plane perpendicular and interpupillary line parallel to the receptor.','Raise the chin.','Centre in the midline at C4.']),
pos('cspine-lateral','Cervical spine','Lateral erect',{kVp:70,mAs:12.5,sidCm:180,grid:false},{...neutral('erect'),bodyYaw:90},'portrait','horizontal'),
pos('cspine-odontoid','Cervical spine','Odontoid open mouth',{kVp:63,mAs:8,sidCm:110,grid:false},{...neutral('supine'),headExtension:5},'portrait','vertical',0,{left:36,right:36,top:42,bottom:42,centreX:0,centreY:-30},['Open mouth view'],['Lie supine and open the mouth as wide as possible.','Align the hard palate perpendicular to the image receptor.','Centre to the back of the open mouth.']),
pos('facial-om','Facial bones','Occipito-mental',{kVp:63,mAs:16,sidCm:110,grid:true},{...neutral('seated'),headExtension:45},'portrait','horizontal',0,{left:30,right:30,top:28,bottom:28,centreX:0,centreY:-28},[],['Sit facing the upright Bucky.','Keep the median sagittal plane perpendicular to the receptor.','Raise the chin until the radiographic baseline is approximately 45° to horizontal.','Centre so the horizontal beam exits at the lower orbital margin.']),
pos('facial-om30','Facial bones','Occipito-mental 30°',{kVp:66,mAs:16,sidCm:110,grid:true},{...neutral('seated'),headExtension:45},'portrait','horizontal',-30,{left:30,right:30,top:28,bottom:28,centreX:0,centreY:-28},[],['Sit facing the upright Bucky.','Raise the chin to the OM position.','Angle the beam caudally 30°.','Centre so the beam exits at the lower orbital margin.']),
pos('lspine-ap','Lumbar spine','AP',{kVp:73,mAs:32,sidCm:110,grid:true},neutral('supine'),'portrait','vertical',0,{left:32,right:32,top:24,bottom:26,centreX:0,centreY:12},[],['Lie supine with the midsagittal plane perpendicular to the receptor.','Centre in the midline at L3, level of the lower costal margins.','Breathe out and hold.'],'arrested-expiration'),
pos('lspine-lateral','Lumbar spine','Lateral',{kVp:90,mAs:40,sidCm:150,grid:true},{...neutral('decubitus'),bodyYaw:90,leftHip:{flexion:35},rightHip:{flexion:35},leftKnee:{flexion:55},rightKnee:{flexion:55}},'portrait','vertical',0,{left:26,right:26,top:24,bottom:26,centreX:8,centreY:12},[],['Lie in lateral decubitus with the median sagittal plane parallel to the receptor.','Keep knees together and bent.','Centre approximately 10 cm anterior to L3 at the lower costal margin.','Breathe out and hold.'],'arrested-expiration'),
pos('tspine-ap','Thoracic spine','AP',{kVp:81,mAs:12,sidCm:110,grid:true},{...neutral('supine'),headExtension:8},'portrait','vertical',0,{left:34,right:34,top:20,bottom:27,centreX:0,centreY:-5},[],['Lie supine with the midsagittal plane perpendicular to the receptor.','Raise the chin slightly.','Centre in the midline midway between the sternal notch and xiphoid process.','Hold your breath in.'],'arrested-inspiration'),
pos('tspine-lateral','Thoracic spine','Lateral',{kVp:81,mAs:40,sidCm:110,grid:true},{...neutral('decubitus'),bodyYaw:90,leftShoulder:{flexion:120},rightShoulder:{flexion:120},leftElbow:{flexion:90},rightElbow:{flexion:90},leftKnee:{flexion:30},rightKnee:{flexion:30}},'portrait','vertical',0,{left:28,right:28,top:18,bottom:24,centreX:7,centreY:-5},[],['Lie in lateral decubitus with the median sagittal plane parallel to the receptor.','Keep palms and elbows together and knees bent.','Centre approximately 5 cm anterior to the T6 spinous process at the axilla level.']),
pos('shoulder-ap','Shoulder','AP',{kVp:60,mAs:4,sidCm:110,grid:false},neutral('erect'),'portrait','horizontal'),pos('humerus-ap','Humerus','AP',{kVp:57,mAs:4,sidCm:110,grid:false}),pos('humerus-lateral','Humerus','Lateral',{kVp:57,mAs:4,sidCm:110,grid:false},{...neutral('supine'),leftShoulder:{rotation:90}}),pos('elbow-ap','Elbow','AP',{kVp:57,mAs:3,sidCm:110,grid:false}),pos('elbow-lateral','Elbow','Lateral',{kVp:57,mAs:3,sidCm:110,grid:false},{...neutral('seated'),leftElbow:{flexion:90}}),pos('forearm-ap','Forearm','AP',{kVp:57,mAs:3,sidCm:110,grid:false}),pos('forearm-lateral','Forearm','Lateral',{kVp:57,mAs:3,sidCm:110,grid:false},{...neutral('seated'),leftElbow:{flexion:90}}),pos('wrist-pa','Wrist','PA',{kVp:55,mAs:2,sidCm:110,grid:false},neutral('seated')),pos('wrist-lateral','Wrist','Lateral',{kVp:55,mAs:2.5,sidCm:110,grid:false},neutral('seated')),pos('hand-pa','Hand','PA',{kVp:52,mAs:2,sidCm:110,grid:false},neutral('seated')),pos('hand-oblique','Hand','Oblique',{kVp:52,mAs:2,sidCm:110,grid:false},neutral('seated')),pos('hip-ap','Hip','AP',{kVp:73,mAs:25,sidCm:110,grid:true},neutral('supine')),pos('femur-ap','Femur','AP',{kVp:70,mAs:8,sidCm:110,grid:false}),pos('femur-lateral','Femur','Lateral',{kVp:70,mAs:8,sidCm:110,grid:false},{...neutral('supine'),bodyYaw:90}),
pos('knee-ap','Knee','AP',{kVp:63,mAs:4,sidCm:110,grid:false},neutral('supine'),'portrait','vertical',0,{left:34,right:34,top:30,bottom:30,centreX:0,centreY:27},['Knee extended; femoral condyles equidistant'],['Lie supine with the posterior knee in contact with the receptor.','Keep the knee extended.','Adjust rotation until the femoral condyles are equidistant from the receptor.','Centre 2.5 cm distal to the apex of the patella in the midline.']),
pos('knee-lateral','Knee','Lateral',{kVp:63,mAs:4,sidCm:110,grid:false},{...neutral('decubitus'),bodyYaw:90,leftKnee:{flexion:30}}),pos('tibfib-ap','Tibia/fibula','AP',{kVp:60,mAs:4,sidCm:110,grid:false}),pos('tibfib-lateral','Tibia/fibula','Lateral',{kVp:60,mAs:4,sidCm:110,grid:false},{...neutral('supine'),bodyYaw:90}),pos('ankle-ap','Ankle','AP',{kVp:60,mAs:3,sidCm:110,grid:false}),pos('ankle-mortise','Ankle','Mortise',{kVp:60,mAs:3,sidCm:110,grid:false},{...neutral('supine'),leftHip:{rotation:-15}}),pos('ankle-lateral','Ankle','Lateral',{kVp:60,mAs:3,sidCm:110,grid:false},{...neutral('supine'),bodyYaw:90}),pos('foot-dp','Foot','DP',{kVp:57,mAs:2,sidCm:110,grid:false}),pos('foot-oblique','Foot','Oblique',{kVp:57,mAs:2,sidCm:110,grid:false},{...neutral('supine'),leftHip:{rotation:30}}),pos('foot-lateral','Foot','Lateral',{kVp:57,mAs:2,sidCm:110,grid:false},{...neutral('supine'),bodyYaw:90})];export function positionsForRegion(region:string){return RADIOGRAPHIC_POSITIONS.filter(p=>p.region.toLowerCase()===region.toLowerCase())}
