export interface PositioningReference{positionId:string;centering:string;collimation:string[];instructions:string[];respiration?:'arrested-inspiration'|'arrested-expiration';source:'user-positioning-reference'}
export const POSITIONING_REFERENCES:PositioningReference[]=[
{positionId:'knee-ap',centering:'2.5 cm distal to the apex of the patella in the midline.',collimation:['Proximally: distal third of femur','Distally: proximal third of tibia/fibula','Laterally: skin margins'],instructions:['Patient supine with posterior knee in contact with image receptor.','Extend the knee.','Adjust leg so femoral condyles are equidistant from the image receptor.'],source:'user-positioning-reference'},
{positionId:'facial-om',centering:'Horizontal beam so the beam exits at the lower orbital margin.',collimation:['Superiorly: skin margins','Laterally: skin margins','Inferiorly: inferior aspect of skull'],instructions:['Patient seated facing upright bucky.','Median sagittal plane perpendicular to image receptor.','External auditory meati and outer canthi equidistant from image receptor.','Symphysis menti touching the bucky; raise chin so radiographic baseline is 45° from horizontal.'],source:'user-positioning-reference'},
{positionId:'facial-om30',centering:'Beam exits at the lower orbital margin.',collimation:['Superiorly: skin margins','Laterally: skin margins','Inferiorly: inferior aspect of skull'],instructions:['Patient seated facing upright bucky.','Median sagittal plane perpendicular to image receptor.','Raise chin so radiographic baseline is 45° from horizontal.','Use 30° caudal beam angle.'],source:'user-positioning-reference'},
{positionId:'lspine-ap',centering:'Midline at L3, approximately the level of the lower costal margins.',collimation:['Superiorly: T12/L1 junction','Inferiorly: sacrum','Laterally: sacroiliac joints'],instructions:['Patient supine with midsagittal plane perpendicular to image receptor.','Hands on chest or by patient side.','Breathe out and hold.'],respiration:'arrested-expiration',source:'user-positioning-reference'},
{positionId:'lspine-lateral',centering:'Approximately 10 cm anterior to L3 at the level of the lower costal margin.',collimation:['Superiorly: T12/L1 junction','Inferiorly: sacrum','Anteriorly: lumbar vertebral bodies','Posteriorly: lumbar spinous processes'],instructions:['Patient lateral decubitus with median sagittal plane parallel to image receptor.','Palms and elbows together.','Knees together and bent to straighten lumbar spine.','Breathe out and hold.'],respiration:'arrested-expiration',source:'user-positioning-reference'},
{positionId:'tspine-ap',centering:'Midline, midway between the sternal notch and xiphoid process.',collimation:['Superiorly: C7/T1 junction','Inferiorly: T12/L1 junction','Laterally: transverse processes'],instructions:['Patient supine with midsagittal plane perpendicular to image receptor.','Raise chin slightly to avoid superimposition.','Hold breath during exposure.'],respiration:'arrested-inspiration',source:'user-positioning-reference'},
{positionId:'tspine-lateral',centering:'Approximately 5 cm anterior to the T6 spinous process at axillary level.',collimation:['Superiorly: C7/T1 junction','Inferiorly: T12/L1 junction','Anteriorly: thoracic vertebral bodies','Posteriorly: thoracic spinous processes'],instructions:['Patient lateral decubitus with median sagittal plane parallel to image receptor.','Palms and elbows together.','Knee bent and ankles together.'],source:'user-positioning-reference'},
{positionId:'cspine-odontoid',centering:'Vertical beam centred to the back of the open mouth.',collimation:['Include lateral masses of atlas','Include body and odontoid process of axis'],instructions:['Open mouth as wide as possible.','Hard palate perpendicular to image receptor; compensate with tube angle if immobilisation prevents this.'],source:'user-positioning-reference'},
{positionId:'cspine-ap',centering:'Midline at C4.',collimation:['Superiorly: base of skull','Inferiorly: T1','Laterally: soft-tissue borders'],instructions:['Patient erect in AP orientation.','Midsagittal plane perpendicular to image receptor.','Interpupillary line parallel to image receptor.','Raise chin to superimpose occlusal plane over base of skull.','Use approximately 15° cranial tube angle.'],source:'user-positioning-reference'}
];
export const EXPOSURE_REFERENCE={chestPA:{kVp:125,mAs:null,sidCm:180,grid:true,aec:true},chestAP:{kVp:96,mAs:1.6,sidCm:180,grid:false},abdomen:{kVp:73,mAs:25,sidCm:110,grid:true},hand:{kVp:52,mAs:2,sidCm:110,grid:false},wristDP:{kVp:55,mAs:2,sidCm:110,grid:false},wristLateral:{kVp:55,mAs:2.5,sidCm:110,grid:false},elbow:{kVp:57,mAs:3,sidCm:110,grid:false},humerus:{kVp:57,mAs:4,sidCm:110,grid:false},shoulderAP:{kVp:60,mAs:4,sidCm:110,grid:false},shoulderAxial:{kVp:66,mAs:8,sidCm:110,grid:false},shoulderModifiedAxial:{kVp:66,mAs:10,sidCm:110,grid:false},foot:{kVp:57,mAs:2,sidCm:110,grid:false},ankle:{kVp:60,mAs:3,sidCm:110,grid:false},knee:{kVp:63,mAs:4,sidCm:110,grid:false},tibFib:{kVp:60,mAs:4,sidCm:110,grid:false},femur:{kVp:70,mAs:8,sidCm:110,grid:false},calcaneumAxial:{kVp:66,mAs:6.3,sidCm:110,grid:false},pelvis:{kVp:73,mAs:25,sidCm:110,grid:true},lateralHipHBL:{kVp:80,mAs:80,sidCm:150,grid:true},facialBones:{kVp:66,mAs:16,sidCm:110,grid:true},cspineLateral:{kVp:70,mAs:12.5,sidCm:180,grid:false},odontoid:{kVp:63,mAs:8,sidCm:110,grid:false},lspineAP:{kVp:73,mAs:32,sidCm:110,grid:true},lspineLateral:{kVp:90,mAs:40,sidCm:150,grid:true},tspineAP:{kVp:81,mAs:12,sidCm:110,grid:true},tspineLateral:{kVp:81,mAs:40,sidCm:110,grid:true}} as const;
