import type{TeachingVolume}from'./teaching-volume';
import type{ProjectionView}from'./drr';
import type{FullBodyPose}from'./radiographic-positions';
export interface ScoutOptions{view:ProjectionView;rotationDeg:number;centreXPercent:number;centreYPercent:number;pose?:FullBodyPose}
function sample(v:TeachingVolume,x:number,y:number,z:number){const[nx,ny,nz]=v.source.manifest.dimensions,xi=Math.round(x),yi=Math.round(y),zi=Math.round(z);if(xi<0||yi<0||zi<0||xi>=nx||yi>=ny||zi>=nz)return-1024;return v.huAt(xi,yi,zi)}
function anatomyScout(v:TeachingVolume,o:ScoutOptions){const[nx,ny,nz]=v.source.manifest.dimensions,lateral=o.view==='LATERAL',width=lateral?ny:nx,height=nz,pixels=new Uint8ClampedArray(width*height),cx=(nx-1)/2,cy=(ny-1)/2,a=o.rotationDeg*Math.PI/180,c=Math.cos(a),s=Math.sin(a),shiftX=o.centreXPercent/100*width,shiftY=o.centreYPercent/100*height,depth=lateral?nx:ny;for(let j=0;j<height;j++)for(let i=0;i<width;i++){let bodyCount=0,boneCount=0,softSum=0,softN=0;for(let d=0;d<depth;d+=3){let x:number,y:number;if(lateral){x=d;y=i-shiftX}else{x=i-shiftX;y=d}const dx=x-cx,dy=y-cy,rx=c*dx-s*dy+cx,ry=s*dx+c*dy+cy,hu=sample(v,rx,ry,j+shiftY);if(hu>-650){bodyCount++;if(hu>180)boneCount++;if(hu>-200&&hu<180){softSum+=hu;softN++}}}if(!bodyCount){pixels[j*width+i]=10;continue}const thickness=Math.min(1,bodyCount/(depth/7)),bone=Math.min(1,boneCount/5),soft=softN?Math.max(0,Math.min(1,(softSum/softN+150)/300)):.3;pixels[j*width+i]=Math.round(42+80*thickness+68*bone+24*soft)}const flipped=new Uint8ClampedArray(pixels.length);for(let y=0;y<height;y++)flipped.set(pixels.subarray((height-1-y)*width,(height-y)*width),y*width);return{width,height,pixels:flipped}}
function line(p:Uint8ClampedArray,w:number,h:number,x0:number,y0:number,x1:number,y1:number,r:number,value:number){const dx=x1-x0,dy=y1-y0,n=Math.max(1,Math.ceil(Math.hypot(dx,dy)));for(let k=0;k<=n;k++){const x=Math.round(x0+dx*k/n),y=Math.round(y0+dy*k/n);for(let yy=y-r;yy<=y+r;yy++)for(let xx=x-r;xx<=x+r;xx++)if(xx>=0&&yy>=0&&xx<w&&yy<h&&(xx-x)**2+(yy-y)**2<=r*r)p[yy*w+xx]=Math.max(p[yy*w+xx],value)}}
function articulatedOverlay(p:Uint8ClampedArray,w:number,h:number,pose:FullBodyPose){const cx=w*.5,headY=h*.09,shoulderY=h*.2,hipY=h*.52,kneeY=h*.73,ankleY=h*.94,sw=w*.15,hw=w*.09,raised=(pose.leftShoulder.flexion??0)>100||(pose.rightShoulder.flexion??0)>100;line(p,w,h,cx,headY,cx,hipY,Math.max(2,w*.035),185);line(p,w,h,cx-hw,shoulderY,cx+hw,shoulderY,Math.max(2,w*.025),195);if(raised){line(p,w,h,cx-hw,shoulderY,cx-sw*.9,h*.03,Math.max(2,w*.025),175);line(p,w,h,cx+hw,shoulderY,cx+sw*.9,h*.03,Math.max(2,w*.025),175)}else{line(p,w,h,cx-hw,shoulderY,cx-sw,hipY*.88,Math.max(2,w*.025),175);line(p,w,h,cx+hw,shoulderY,cx+sw,hipY*.88,Math.max(2,w*.025),175)}const lk=pose.leftKnee.flexion??0,rk=pose.rightKnee.flexion??0;line(p,w,h,cx-w*.045,hipY,cx-w*(lk? .12:.055),kneeY,Math.max(2,w*.03),180);line(p,w,h,cx+w*.045,hipY,cx+w*(rk? .12:.055),kneeY,Math.max(2,w*.03),180);line(p,w,h,cx-w*(lk?.12:.055),kneeY,cx-w*(lk?.2:.06),ankleY,Math.max(2,w*.025),170);line(p,w,h,cx+w*(rk?.12:.055),kneeY,cx+w*(rk?.2:.06),ankleY,Math.max(2,w*.025),170);line(p,w,h,cx,headY,cx,headY+h*.06,Math.max(3,w*.06),200)}
export function positioningScout(v:TeachingVolume,o:ScoutOptions){const out=anatomyScout(v,o);if(o.pose)articulatedOverlay(out.pixels,out.width,out.height,o.pose);return out}
