import type{RadiographicPosition}from'./radiographic-positions';
export type CritiqueLevel='good'|'review'|'poor';
export interface CritiqueItem{id:string;label:string;level:CritiqueLevel;feedback:string}
export interface TechniqueSnapshot{rotationDeg:number;centreXPercent:number;centreYPercent:number;collimation:{left:number;right:number;top:number;bottom:number};kVp:number;mAs:number;sidCm:number}
export interface ImageCritique{score:number;items:CritiqueItem[];summary:string}
interface Rule{rotationTolerance?:number;centreTolerance?:number;coverage:string[];positioning:string[]}
const rules:Record<string,Rule>={
 'chest-pa-erect':{rotationTolerance:4,centreTolerance:8,coverage:['Include both lung apices and both costophrenic angles.'],positioning:['SC joints should be equidistant from the spinous processes.','Scapulae should be projected clear of the lung fields.','Adequate inspiration should show approximately 10–11 posterior ribs above the diaphragm.']},
 'chest-lateral-erect':{rotationTolerance:4,centreTolerance:8,coverage:['Include apices and posterior costophrenic angles.'],positioning:['Posterior ribs and costophrenic angles should be closely superimposed.','Arms and humeri must be raised clear of the apices.','Centre at the midthorax around T7.']},
 'hand-pa':{rotationTolerance:4,centreTolerance:10,coverage:['Include all phalanges, metacarpals and carpal region.'],positioning:['Phalanges and metacarpals should show symmetric shaft concavity without rotation.','IP and MCP joints should be open with the fingers flat.','Digits should be slightly separated without soft-tissue overlap.']},
 'wrist-pa':{rotationTolerance:4,centreTolerance:10,coverage:['Include distal radius/ulna, carpals and proximal metacarpals.'],positioning:['Wrist, forearm and elbow should remain in the same horizontal plane.','Distal radioulnar and radiocarpal joint spaces should be open.','Avoid radial or ulnar deviation.']},
 'forearm-ap':{rotationTolerance:5,centreTolerance:10,coverage:['Include the elbow and wrist joints on the same exposure.'],positioning:['Radius and ulna should be approximately parallel with minimal shaft superimposition.','Humeral epicondyles should be parallel to the receptor.']},
 'elbow-ap':{rotationTolerance:5,centreTolerance:10,coverage:['Include distal humerus and proximal radius/ulna.'],positioning:['Humeroulnar and humeroradial joint spaces should appear open.','Epicondyles should be non-rotated.','Only slight proximal-ulna superimposition of the radial head/neck is expected.']},
 'shoulder-ap':{rotationTolerance:7,centreTolerance:10,coverage:['Include the proximal humerus, glenohumeral joint and shoulder girdle.'],positioning:['For external rotation, the greater tuberosity should be in profile laterally.','The humeral head should only slightly overlap the glenoid.']},
 'knee-ap':{rotationTolerance:5,centreTolerance:8,coverage:['Include distal femur, proximal tibia/fibula and patella.'],positioning:['Femorotibial joint space should be open and symmetric.','Patella should be centred between the femoral condyles.','Tibial plateaus should appear sharp without avoidable foreshortening.']},
 'knee-lateral':{rotationTolerance:4,centreTolerance:8,coverage:['Include distal femur, proximal tibia/fibula and patella.'],positioning:['Femoral condyles should be directly superimposed.','Patellofemoral joint space should be open.','Knee flexion should be approximately 20–30 degrees.']},
 'pelvis-ap':{rotationTolerance:4,centreTolerance:8,coverage:['Include the complete pelvis and proximal femora.'],positioning:['Iliac wings and obturator foramina should be symmetric.','Femoral necks should be demonstrated without foreshortening.','Lesser trochanters should be absent or minimally visible.']},
 'cspine-ap':{rotationTolerance:4,centreTolerance:8,coverage:['Include C3 through T1.'],positioning:['Spinous processes should align with the vertebral midline.','Intervertebral spaces from C3 to T1 should be open where technique permits.','Mandible/skull base should not obscure C3 and below.']},
 'lspine-ap':{rotationTolerance:4,centreTolerance:8,coverage:['Include the T12/L1 junction through the sacrum.'],positioning:['Spinous processes should be centred over vertebral bodies.','Pedicles should be equidistant from the vertebral body margins.']}
};
const pct=(actual:number,target:number)=>Math.abs(actual-target)/Math.max(1,Math.abs(target));
function exposure(position:RadiographicPosition,t:TechniqueSnapshot):CritiqueItem[]{const p=position.exposure,k=pct(t.kVp,p.kVp),m=pct(t.mAs,p.mAs),s=pct(t.sidCm,p.sidCm),out:CritiqueItem[]=[];
 out.push({id:'kvp',label:'Penetration / kVp',level:k<=.08?'good':k<=.2?'review':'poor',feedback:k<=.08?`kVp is close to the ${p.kVp} kVp teaching preset.`:t.kVp<p.kVp?'Lower kVp reduces penetration and tends to increase subject contrast; review whether anatomy is adequately penetrated.':'Higher kVp increases penetration and tube output; review loss of subject contrast and unnecessary exposure.'});
 out.push({id:'mas',label:'Photon quantity / mAs',level:m<=.15?'good':m<=.4?'review':'poor',feedback:m<=.15?`mAs is close to the ${p.mAs} mAs teaching preset.`:t.mAs<p.mAs?'Reduced mAs lowers photon quantity and should increase quantum mottle/noise.':'Increased mAs raises photon quantity and patient exposure; use only what is required for adequate image quality.'});
 out.push({id:'sid',label:'SID',level:s<=.05?'good':s<=.15?'review':'poor',feedback:s<=.05?`SID is close to the ${p.sidCm} cm preset.`:t.sidCm>p.sidCm?'Longer SID reduces detector fluence by inverse-square behaviour unless technique is compensated.':'Shorter SID increases detector fluence and changes magnification/geometric behaviour.'});return out}
export function critiqueRadiograph(position:RadiographicPosition,t:TechniqueSnapshot):ImageCritique{const r=rules[position.id],items=exposure(position,t),rot=Math.abs(t.rotationDeg-position.pose.bodyYaw),centre=Math.hypot(t.centreXPercent-position.startingField.centreX,t.centreYPercent-position.startingField.centreY),field=(100-t.collimation.left-t.collimation.right)*(100-t.collimation.top-t.collimation.bottom)/10000;
 if(r){items.unshift({id:'rotation',label:'Rotation',level:rot<=(r.rotationTolerance??5)?'good':rot<=2*(r.rotationTolerance??5)?'review':'poor',feedback:rot<=(r.rotationTolerance??5)?'Rotation is close to the projection preset.':`Rotation differs by ${rot.toFixed(0)}° from the projection setup. ${r.positioning[0]}`},{id:'centring',label:'Centring',level:centre<=(r.centreTolerance??10)?'good':centre<=20?'review':'poor',feedback:centre<=(r.centreTolerance??10)?'Central ray position is close to the teaching target.':`Central ray is ${centre.toFixed(0)} percentage points from the teaching target. ${r.coverage[0]}`});}
 items.push({id:'collimation',label:'Collimation',level:field>.08&&field<.55?'good':field<=.75?'review':'poor',feedback:field>.08&&field<.55?'Field size is reasonably restricted for this simulation.':field>=.55?'Field is broad. Collimate to the anatomy required while preserving all essential coverage.':'Field may be too tight. Confirm all required anatomy is included before exposure.'});
 const values={good:1,review:.55,poor:0},score=Math.round(items.reduce((a,i)=>a+values[i.level],0)/items.length*100),summary=score>=85?'Technically strong image. Confirm the projection-specific anatomical criteria before accepting it.':score>=65?'Usable attempt with specific technique points to review before acceptance.':'Repeat the technique review before accepting this image.';return{score,items,summary}}
export function teachingCriteria(positionId:string){return rules[positionId]??null}
