export type XrayQuality='diagnostic'|'limited'|'non-diagnostic';
export interface XrayTechnique{projection:string;kVp:[number,number];mAs:[number,number];sidCm:[number,number];centreTolerancePercent:number;rotationToleranceDeg:number;coverage:string[]}
export interface XrayLearningCase{id:string;title:string;region:string;views:string[];pathology:string;teachingPoints:string[];goldStandardAppearance:string[];technique:XrayTechnique}
export interface XrayAttempt{projection:string;kVp:number;mAs:number;sidCm:number;centreErrorPercent:number;rotationErrorDeg:number;coverageComplete:boolean;motion:boolean}
export interface XrayFeedback{quality:XrayQuality;issues:string[];improvements:string[]}
export const XRAY_CASES:XrayLearningCase[]=[
{id:'normal-chest-pa-lat',title:'Normal chest',region:'Chest',views:['PA','Lateral'],pathology:'Normal',teachingPoints:['Assess inspiration, rotation, exposure and coverage before interpretation.'],goldStandardAppearance:['PA chest with adequate inspiration and no significant rotation','Lateral view includes retrosternal and retrocardiac regions'],technique:{projection:'PA',kVp:[105,130],mAs:[1,8],sidCm:[170,200],centreTolerancePercent:8,rotationToleranceDeg:4,coverage:['apices','costophrenic-angles']}},
{id:'pneumothorax-chest',title:'Pneumothorax',region:'Chest',views:['PA','AP'],pathology:'Pneumothorax',teachingPoints:['Search for a visceral pleural line and absence of peripheral lung markings.'],goldStandardAppearance:['Visible visceral pleural edge','Peripheral hyperlucency without lung markings'],technique:{projection:'PA',kVp:[105,130],mAs:[1,8],sidCm:[170,200],centreTolerancePercent:8,rotationToleranceDeg:4,coverage:['apices','costophrenic-angles']}},
{id:'pleural-effusion-chest',title:'Pleural effusion',region:'Chest',views:['PA','Lateral'],pathology:'Pleural effusion',teachingPoints:['Assess costophrenic angles and dependent pleural space.'],goldStandardAppearance:['Blunting of costophrenic angle','Dependent homogeneous opacity/meniscus when sufficiently large'],technique:{projection:'PA',kVp:[105,130],mAs:[1,8],sidCm:[170,200],centreTolerancePercent:8,rotationToleranceDeg:4,coverage:['apices','costophrenic-angles']}},
{id:'volar-plate-finger',title:'Volar plate injury',region:'Finger',views:['PA','Lateral'],pathology:'Volar plate avulsion injury',teachingPoints:['One trauma projection is insufficient; inspect the base of the middle phalanx on the lateral view.'],goldStandardAppearance:['Soft-tissue swelling','Small avulsion fragment at the volar base of the middle phalanx may be most conspicuous laterally'],technique:{projection:'Lateral',kVp:[50,65],mAs:[1,5],sidCm:[90,120],centreTolerancePercent:7,rotationToleranceDeg:5,coverage:['affected-digit','adjacent-joint']}},
{id:'knee-trauma-ap-lat',title:'Knee trauma',region:'Knee',views:['AP','Lateral'],pathology:'Trauma case',teachingPoints:['Use orthogonal views and assess alignment, cortex and joint spaces.'],goldStandardAppearance:['AP demonstrates tibiofemoral alignment','Lateral demonstrates patellofemoral relationship and suprapatellar region'],technique:{projection:'AP',kVp:[60,80],mAs:[2,12],sidCm:[90,120],centreTolerancePercent:7,rotationToleranceDeg:5,coverage:['distal-femur','proximal-tibia-fibula','patella']}},
{id:'ankle-trauma',title:'Ankle trauma',region:'Ankle',views:['AP','Mortise','Lateral'],pathology:'Trauma case',teachingPoints:['The mortise view should demonstrate the ankle joint with appropriate rotation.'],goldStandardAppearance:['AP and mortise demonstrate distal tibia/fibula and talus','Lateral demonstrates talar and calcaneal relationships'],technique:{projection:'Mortise',kVp:[50,70],mAs:[1,8],sidCm:[90,120],centreTolerancePercent:7,rotationToleranceDeg:5,coverage:['distal-tibia-fibula','talus','ankle-joint']}}
];
export function assessXrayAttempt(c:XrayLearningCase,a:XrayAttempt):XrayFeedback{const issues:string[]=[],improvements:string[]=[];if(a.projection.toLowerCase()!==c.technique.projection.toLowerCase()){issues.push('Incorrect projection for the assessed view.');improvements.push(`Position for the ${c.technique.projection} projection.`)}if(a.centreErrorPercent>c.technique.centreTolerancePercent){issues.push('Centring is outside the acceptable region.');improvements.push('Re-centre the central ray to the required anatomical landmark.')}if(a.rotationErrorDeg>c.technique.rotationToleranceDeg){issues.push('Patient/part rotation is outside tolerance.');improvements.push('Correct patient or limb rotation before exposure.')}if(a.kVp<c.technique.kVp[0]){issues.push('kVp is too low for this case.');improvements.push('Increase kVp to provide adequate penetration.')}else if(a.kVp>c.technique.kVp[1]){issues.push('kVp is too high for this case.');improvements.push('Reduce kVp to the expected technique range.')}if(a.mAs<c.technique.mAs[0]){issues.push('mAs is too low, increasing quantum noise.');improvements.push('Increase mAs while applying dose optimisation principles.')}else if(a.mAs>c.technique.mAs[1]){issues.push('mAs is higher than required.');improvements.push('Reduce mAs while maintaining diagnostic image quality.')}if(a.sidCm<c.technique.sidCm[0]||a.sidCm>c.technique.sidCm[1]){issues.push('SID is outside the expected range.');improvements.push('Set the appropriate source-to-image distance.')}if(!a.coverageComplete){issues.push('Required anatomy is excluded by positioning or collimation.');improvements.push(`Include: ${c.technique.coverage.join(', ')}.`)}if(a.motion){issues.push('Motion degrades anatomical sharpness.');improvements.push('Stabilise the patient/part and repeat breathing or movement instructions.')}const severe=!a.coverageComplete||a.centreErrorPercent>c.technique.centreTolerancePercent*2||a.motion;return{quality:severe?'non-diagnostic':issues.length?'limited':'diagnostic',issues,improvements}}
