import{detectorGeometry,projectVolume}from'../src/core/drr';
import type{TeachingVolume}from'../src/core/teaching-volume';
import{createAcquisitionState,projectionOptions}from'../src/core/acquisition-geometry';
import{RADIOGRAPHIC_POSITIONS}from'../src/core/radiographic-positions';
const manifest={dimensions:[117,91,105],spacingMm:[3,3,3.0054945055]} as any;
const volume={source:{manifest}} as TeachingVolume;
const near=detectorGeometry(volume,{view:'PA',kVp:125,mAs:2,sidCm:100}),far=detectorGeometry(volume,{view:'PA',kVp:125,mAs:2,sidCm:180});
if(!(near.magnification>far.magnification&&near.inverseSquare>far.inverseSquare))throw new Error('DRR SID geometry regression: shorter SID must increase magnification and detector fluence');
if(!(far.magnification>1&&Number.isFinite(far.magnification)))throw new Error('DRR magnification must be finite and > 1');
const airVolume={source:{manifest:{dimensions:[20,20,30],spacingMm:[2,2,2]}},huAt:()=>-1000}as unknown as TeachingVolume;
const air=projectVolume(airVolume,{kVp:125,mAs:2,sidCm:180,view:'PA',seed:17,collimation:{left:0,right:0,top:0,bottom:0}});
const detectorCoverage=air.pixels.filter(value=>value>8).length/air.pixels.length;
if(detectorCoverage<.99)throw new Error(`DRR exposed-air regression: detector coverage ${(detectorCoverage*100).toFixed(1)}% must exceed 99%`);
const pa=RADIOGRAPHIC_POSITIONS.find(position=>position.region==='Chest'&&position.projection.toUpperCase().startsWith('PA'))!;
const paField=(1-(pa.startingField.left+pa.startingField.right)/100)*(1-(pa.startingField.top+pa.startingField.bottom)/100);
if(paField<.7)throw new Error(`PA chest starting field occupies only ${(paField*100).toFixed(1)}% of the detector`);
const state=createAcquisitionState({position:pa,patientSex:'male',bodyYawDeg:7,patientXPercent:3,patientYPercent:-2,beamXPercent:11,beamYPercent:5,tubeAngleDeg:4,sidCm:180,kVp:125,mAs:2,collimation:{left:10,right:12,top:8,bottom:9}}),options=projectionOptions(state);
if(state.examination.view!=='PA'||state.source.positionMm[1]<=0||state.detector.normal[1]<=0)throw new Error('PA acquisition state must place source and detector normal on the anterior axis');
if(options.rotationDeg!==7||options.centreXPercent!==8||options.centreYPercent!==7)throw new Error('DRR options must preserve patient rotation and beam-to-patient displacement');
if(options.detectorWidthCm!==35||options.detectorHeightCm!==43||options.kVp!==125||options.mAs!==2)throw new Error('DRR options must preserve detector and exposure state');
const tissueManifest={dimensions:[117,91,105],spacingMm:[3,3,3.0054945055]} as any;
const tissue={source:{manifest:tissueManifest},huAt:(x:number,y:number,z:number)=>x>8&&x<108&&y>8&&y<82&&z>5&&z<100?0:-1000}as unknown as TeachingVolume;
const chest=projectVolume(tissue,{kVp:125,mAs:2,sidCm:180,view:'PA',seed:17,collimation:{left:6,right:6,top:7,bottom:9}});
if(!chest.anatomyBounds||chest.anatomyBounds.width/chest.width<.65||chest.anatomyBounds.height/chest.height<.55)throw new Error('DRR anatomy footprint regression: chest-sized anatomy must occupy the detector at physical scale');
console.log('Validated DRR geometry invariants.');
